# Using Pre-Trained Model

In [1]:
!pip install -q transformers sentencepiece nltk rouge-score

from transformers import MarianMTModel, MarianTokenizer
from nltk.translate.bleu_score import sentence_bleu
from rouge_score import rouge_scorer
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

english_sentences = [
    "hello", "how are you", "i am fine", "what is your name", "nice to meet you",
    "i love machine learning", "do you like pizza", "good morning", "thank you", "see you later"
]
french_sentences = [
    "bonjour", "comment ça va", "je vais bien", "quel est ton nom", "ravi de vous rencontrer",
    "j'aime l'apprentissage automatique", "aimes-tu la pizza", "bonjour", "merci", "à plus tard"
]

model_name = "Helsinki-NLP/opus-mt-en-fr"
tokenizer = MarianTokenizer.from_pretrained(model_name)
model = MarianMTModel.from_pretrained(model_name)

results = []
for i, src in enumerate(english_sentences):
    inputs = tokenizer(src, return_tensors="pt", padding=True)
    translated = model.generate(**inputs)
    tgt = tokenizer.decode(translated[0], skip_special_tokens=True)

    reference = [nltk.word_tokenize(french_sentences[i])]
    prediction = nltk.word_tokenize(tgt)
    bleu = sentence_bleu(reference, prediction)
    rouge = rouge_scorer.RougeScorer(['rouge1', 'rouge2'], use_stemmer=True).score(
        ' '.join(reference[0]), ' '.join(prediction))

    results.append({
        "English": src,
        "French (Reference)": french_sentences[i],
        "Predicted French": tgt,
        "BLEU": round(bleu, 4),
        "ROUGE-1": round(rouge['rouge1'].fmeasure, 4),
        "ROUGE-2": round(rouge['rouge2'].fmeasure, 4)
    })

import pandas as pd
pd.DataFrame(results)

  Preparing metadata (setup.py) ... done
  Building wheel for rouge-score (setup.py) ... done

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer_config.json:   0%|          | 0.00/42.0 [00:00<?, ?B/s]

source.spm:   0%|          | 0.00/778k [00:00<?, ?B/s]

target.spm:   0%|          | 0.00/802k [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

/usr/local/lib/python3.12/dist-packages/transformers/models/marian/tokenization_marian.py:176: UserWarning: Recommended: pip install sacremoses.
  warnings.warn("Recommended: pip install sacremoses.")

config.json: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/301M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/258 [00:00<?, ?it/s]

model.safetensors:   0%|          | 0.00/301M [00:00<?, ?B/s]

The tied weights mapping and config for this model specifies to tie model.shared.weight to model.decoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie model.shared.weight to model.encoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

generation_config.json:   0%|          | 0.00/293 [00:00<?, ?B/s]

/usr/local/lib/python3.12/dist-packages/nltk/translate/bleu_score.py:577: UserWarning:
The hypothesis contains 0 counts of 2-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
/usr/local/lib/python3.12/dist-packages/nltk/translate/bleu_score.py:577: UserWarning:
The hypothesis contains 0 counts of 3-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
/usr/local/lib/python3.12/dist-packages/nltk/translate/bleu_score.py:577: UserWarning:
The hypothesis contains 0 counts of 4-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)

,English,French (Reference),Predicted French,BLEU,ROUGE-1,ROUGE-2
0,hello,bonjour,Bonjour.,0.0,1.0000,0.0000
1,how are you,comment ça va,comment allez-vous,0.0,0.3333,0.0000
2,i am fine,je vais bien,Je vais bien.,0.0,1.0000,1.0000
3,what is your name,quel est ton nom,quel est votre nom,0.0,0.7500,0.3333
4,nice to meet you,ravi de vous rencontrer,Ravie de vous rencontrer.,0.0,1.0000,1.0000
5,i love machine learning,j'aime l'apprentissage automatique,J'adore l'apprentissage automatique,0.0,0.8000,0.5000
6,do you like pizza,aimes-tu la pizza,Tu aimes les pizzas ?,0.0,0.7500,0.0000
7,good morning,bonjour,Bonjour.,0.0,1.0000,0.0000
8,thank you,merci,Je vous remercie.,0.0,0.0000,0.0000
9,see you later,à plus tard,A tout à l'heure.,0.0,0.0000,0.0000

In [2]:
# Step 1: Install and import libraries
!pip install -q datasets nltk rouge-score

from datasets import load_dataset
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
import tensorflow as tf
import nltk
from nltk.translate.bleu_score import sentence_bleu
from rouge_score import rouge_scorer
nltk.download('punkt')

# Step 2: Prepare a small dataset (English-French)
english_sentences = [
    "hello", "how are you", "i am fine", "what is your name", "nice to meet you",
    "i love machine learning", "do you like pizza", "good morning", "thank you", "see you later"
]

french_sentences = [
    "bonjour", "comment ça va", "je vais bien", "quel est ton nom", "ravi de vous rencontrer",
    "j'aime l'apprentissage automatique", "aimes-tu la pizza", "bonjour", "merci", "à plus tard"
]

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [3]:
len(english_sentences)

10

In [4]:


# Step 3: Tokenization
def tokenize(sentences, num_words=10000):
    tokenizer = Tokenizer(num_words=num_words, oov_token='<OOV>')
    tokenizer.fit_on_texts(sentences)
    tensor = tokenizer.texts_to_sequences(sentences)
    return tokenizer, pad_sequences(tensor, padding='post')

en_tokenizer, en_tensor = tokenize(english_sentences)
fr_tokenizer, fr_tensor = tokenize(french_sentences)
input_vocab_size = len(en_tokenizer.word_index) + 1
target_vocab_size = len(fr_tokenizer.word_index) + 1

In [6]:
en_tokenizer.word_index

{'<OOV>': 1,
 'you': 2,
 'i': 3,
 'hello': 4,
 'how': 5,
 'are': 6,
 'am': 7,
 'fine': 8,
 'what': 9,
 'is': 10,
 'your': 11,
 'name': 12,
 'nice': 13,
 'to': 14,
 'meet': 15,
 'love': 16,
 'machine': 17,
 'learning': 18,
 'do': 19,
 'like': 20,
 'pizza': 21,
 'good': 22,
 'morning': 23,
 'thank': 24,
 'see': 25,
 'later': 26}

In [7]:
en_tensor

array([[ 4,  0,  0,  0],
       [ 5,  6,  2,  0],
       [ 3,  7,  8,  0],
       [ 9, 10, 11, 12],
       [13, 14, 15,  2],
       [ 3, 16, 17, 18],
       [19,  2, 20, 21],
       [22, 23,  0,  0],
       [24,  2,  0,  0],
       [25,  2, 26,  0]], dtype=int32)

In [8]:
target_vocab_size

28

In [9]:
fr_tokenizer.word_index

{'<OOV>': 1,
 'bonjour': 2,
 'comment': 3,
 'ça': 4,
 'va': 5,
 'je': 6,
 'vais': 7,
 'bien': 8,
 'quel': 9,
 'est': 10,
 'ton': 11,
 'nom': 12,
 'ravi': 13,
 'de': 14,
 'vous': 15,
 'rencontrer': 16,
 "j'aime": 17,
 "l'apprentissage": 18,
 'automatique': 19,
 'aimes': 20,
 'tu': 21,
 'la': 22,
 'pizza': 23,
 'merci': 24,
 'à': 25,
 'plus': 26,
 'tard': 27}

In [10]:
# Step 4: Define transformer model
class Transformer(tf.keras.Model):
    def __init__(self, input_vocab, target_vocab, d_model, num_heads, dff, pe_input, pe_target):
        super().__init__()
        self.encoder_embedding = tf.keras.layers.Embedding(input_vocab, d_model)
        self.decoder_embedding = tf.keras.layers.Embedding(target_vocab, d_model)
        self.pos_encoding_input = self.positional_encoding(pe_input, d_model)
        self.pos_encoding_target = self.positional_encoding(pe_target, d_model)

        self.enc_layer = tf.keras.layers.MultiHeadAttention(num_heads=num_heads, key_dim=d_model)
        self.dec_layer = tf.keras.layers.MultiHeadAttention(num_heads=num_heads, key_dim=d_model)
        self.dense_proj = tf.keras.Sequential([
            tf.keras.layers.Dense(dff, activation='relu'),
            tf.keras.layers.Dense(d_model)
        ])
        self.final_dense = tf.keras.layers.Dense(target_vocab)

    def positional_encoding(self, max_len, dm):
        pos = np.arange(max_len)[:, np.newaxis]
        i = np.arange(dm)[np.newaxis, :]
        angle_rates = 1 / np.power(10000, (2 * (i//2)) / np.float32(dm))
        angle_rads = pos * angle_rates
        angle_rads[:, 0::2] = np.sin(angle_rads[:, 0::2])
        angle_rads[:, 1::2] = np.cos(angle_rads[:, 1::2])
        return tf.cast(angle_rads, dtype=tf.float32)

    def call(self, inputs, training=False):
        inp, tar = inputs
        enc = self.encoder_embedding(inp) + self.pos_encoding_input[:tf.shape(inp)[1]]
        dec = self.decoder_embedding(tar) + self.pos_encoding_target[:tf.shape(tar)[1]]
        enc_output = self.enc_layer(enc, enc)
        dec_output = self.dec_layer(dec, enc_output)
        final = self.dense_proj(dec_output)
        return self.final_dense(final)

In [11]:


# Step 5: Compile and train
model = Transformer(input_vocab=input_vocab_size, target_vocab=target_vocab_size,
                    d_model=64, num_heads=4, dff=128, pe_input=en_tensor.shape[1], pe_target=fr_tensor.shape[1])
model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])
model.fit([en_tensor, fr_tensor[:, :-1]], fr_tensor[:, 1:], epochs=20, batch_size=32)

Epoch 1/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 12s 12s/step - accuracy: 0.0000e+00 - loss: 3.3306
Epoch 2/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.4333 - loss: 3.2668
Epoch 3/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 180ms/step - accuracy: 0.4333 - loss: 3.1652
Epoch 4/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - accuracy: 0.4333 - loss: 3.0055
Epoch 5/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.4333 - loss: 2.7805
Epoch 6/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step - accuracy: 0.4333 - loss: 2.5750
Epoch 7/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - accuracy: 0.4333 - loss: 2.7348
Epoch 8/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.4333 - loss: 2.6575
Epoch 9/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step - accuracy: 0.4333 - loss: 2.4962
Epoch 10/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step - accuracy: 0.4333 - loss: 2.4643
Epoch 11/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.4333 - loss: 2.4972
Epoch 12/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - accuracy: 0.4333 - loss: 2.5067
Epoch 13/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.4333 - loss: 2.4742
Epoch 14/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step - accuracy: 0.4333 - loss: 2.4139
Epoch 15/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step - accuracy: 0.4333 - loss: 2.3638
Epoch 16/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - accuracy: 0.4333 - loss: 2.3649
Epoch 17/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step - accuracy: 0.4333 - loss: 2.3889
Epoch 18/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.4333 - loss: 2.3667
Epoch 19/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.4333 - loss: 2.3219
Epoch 20/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step - accuracy: 0.4333 - loss: 2.3056

In [12]:

# Step 6: Translation function
def translate(sentence):
    seq = en_tokenizer.texts_to_sequences([sentence])
    padded = pad_sequences(seq, maxlen=en_tensor.shape[1], padding='post')
    decoder_input = np.zeros((1, fr_tensor.shape[1]), dtype=np.int32)
    decoder_input[0][0] = fr_tokenizer.word_index.get('<sos>', 1)

    for i in range(1, fr_tensor.shape[1]):
        output = model([padded, decoder_input[:, :-1]], training=False)
        pred_id = tf.argmax(output[0, i-1]).numpy()
        decoder_input[0][i] = pred_id
        if pred_id == fr_tokenizer.word_index.get('<eos>'):
            break

    return ' '.join([fr_tokenizer.index_word.get(idx, '') for idx in decoder_input[0] if idx != 0])

In [13]:

# Step 7: Evaluation
results = []
for i in range(10):
    ref = [nltk.word_tokenize(french_sentences[i].replace('<sos>', '').replace('<eos>', '').strip())]
    pred = nltk.word_tokenize(translate(english_sentences[i]))
    bleu = sentence_bleu(ref, pred)
    rouge = rouge_scorer.RougeScorer(['rouge1', 'rouge2'], use_stemmer=True).score(' '.join(ref[0]), ' '.join(pred))
    results.append((english_sentences[i], french_sentences[i].replace('<sos>', '').replace('<eos>', '').strip(), ' '.join(pred), bleu, rouge['rouge1'].fmeasure, rouge['rouge2'].fmeasure))

import pandas as pd
pd.DataFrame(results, columns=["English", "French (Reference)", "Predicted French", "BLEU", "ROUGE-1", "ROUGE-2"])

,English,French (Reference),Predicted French,BLEU,ROUGE-1,ROUGE-2
0,hello,bonjour,< OOV >,0,0.0,0.0
1,how are you,comment ça va,< OOV >,0,0.0,0.0
2,i am fine,je vais bien,< OOV >,0,0.0,0.0
3,what is your name,quel est ton nom,< OOV >,0,0.0,0.0
4,nice to meet you,ravi de vous rencontrer,< OOV >,0,0.0,0.0
5,i love machine learning,j'aime l'apprentissage automatique,< OOV >,0,0.0,0.0
6,do you like pizza,aimes-tu la pizza,< OOV >,0,0.0,0.0
7,good morning,bonjour,< OOV >,0,0.0,0.0
8,thank you,merci,< OOV >,0,0.0,0.0
9,see you later,à plus tard,< OOV >,0,0.0,0.0

In [ ]:
# Step 1: Install and import libraries
!pip install -q datasets nltk rouge-score

from datasets import load_dataset
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
import tensorflow as tf
import nltk
from nltk.translate.bleu_score import sentence_bleu
from rouge_score import rouge_scorer
nltk.download('punkt')

# Step 2: Load a real translation dataset (English-French)
data = load_dataset("opus_books", "en-fr", split='train[:10000]')
english_sentences = [f"{x['translation']['en']}" for x in data]
french_sentences = [f"<sos> {x['translation']['fr']} <eos>" for x in data]

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

README.md: 0.00B [00:00, ?B/s]

train-00000-of-00001.parquet:   0%|          | 0.00/21.0M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/127085 [00:00<?, ? examples/s]

In [ ]:
english_sentences[0]

'The Wanderer'

In [ ]:
french_sentences[0]

'<sos> Le grand Meaulnes <eos>'

In [ ]:
len(english_sentences)

10000

In [ ]:

# Step 3: Tokenization
def tokenize(sentences, num_words=10000):
    tokenizer = Tokenizer(num_words=num_words, oov_token='<OOV>')
    tokenizer.fit_on_texts(sentences)
    tensor = tokenizer.texts_to_sequences(sentences)
    return tokenizer, pad_sequences(tensor, padding='post',maxlen=40)

en_tokenizer, en_tensor = tokenize(english_sentences)
fr_tokenizer, fr_tensor = tokenize(french_sentences)
input_vocab_size = len(en_tokenizer.word_index) + 1
target_vocab_size = len(fr_tokenizer.word_index) + 1

In [ ]:
en_tokenizer.word_index

{'<OOV>': 1,
 'the': 2,
 'to': 3,
 'and': 4,
 'of': 5,
 'i': 6,
 'a': 7,
 'in': 8,
 'was': 9,
 'her': 10,
 'he': 11,
 'she': 12,
 'it': 13,
 'that': 14,
 'had': 15,
 'his': 16,
 'not': 17,
 'you': 18,
 'with': 19,
 'as': 20,
 'at': 21,
 'for': 22,
 'on': 23,
 'be': 24,
 'my': 25,
 'but': 26,
 'is': 27,
 'me': 28,
 'have': 29,
 'him': 30,
 'by': 31,
 'which': 32,
 'all': 33,
 'from': 34,
 'were': 35,
 'so': 36,
 'this': 37,
 'they': 38,
 'mr': 39,
 'could': 40,
 'no': 41,
 'been': 42,
 'one': 43,
 'what': 44,
 'would': 45,
 'said': 46,
 'when': 47,
 'we': 48,
 'very': 49,
 "'": 50,
 'there': 51,
 'an': 52,
 'their': 53,
 'them': 54,
 'your': 55,
 'elizabeth': 56,
 'or': 57,
 'who': 58,
 'if': 59,
 'are': 60,
 'will': 61,
 'then': 62,
 'more': 63,
 'do': 64,
 'little': 65,
 'up': 66,
 'out': 67,
 'such': 68,
 'now': 69,
 'must': 70,
 'miss': 71,
 'mrs': 72,
 'time': 73,
 'some': 74,
 'much': 75,
 'am': 76,
 'did': 77,
 'only': 78,
 'than': 79,
 'before': 80,
 'room': 81,
 'darcy': 82,
 'never': 83,
 'any': 84,
 'know': 85,
 'well': 86,
 'other': 87,
 'again': 88,
 'should': 89,
 'meaulnes': 90,
 'like': 91,
 'us': 92,
 'into': 93,
 'how': 94,
 'two': 95,
 'long': 96,
 'after': 97,
 'soon': 98,
 'has': 99,
 'good': 100,
 'jane': 101,
 'first': 102,
 'day': 103,
 'can': 104,
 'see': 105,
 'though': 106,
 'bennet': 107,
 'without': 108,
 'came': 109,
 'back': 110,
 'think': 111,
 'last': 112,
 'too': 113,
 'where': 114,
 'come': 115,
 'go': 116,
 'every': 117,
 'about': 118,
 'most': 119,
 'over': 120,
 'say': 121,
 'might': 122,
 'herself': 123,
 'nothing': 124,
 'way': 125,
 'house': 126,
 'bingley': 127,
 'went': 128,
 'own': 129,
 'young': 130,
 'down': 131,
 'made': 132,
 'great': 133,
 'man': 134,
 'make': 135,
 'being': 136,
 'shall': 137,
 'thought': 138,
 'our': 139,
 'away': 140,
 'lady': 141,
 'its': 142,
 'himself': 143,
 'may': 144,
 'while': 145,
 'heard': 146,
 'once': 147,
 'door': 148,
 'saw': 149,
 'always': 150,
 'ever': 151,
 'these': 152,
 'looked': 153,
 'still': 154,
 'evening': 155,
 'sister': 156,
 'off': 157,
 'just': 158,
 'morning': 159,
 'here': 160,
 'dear': 161,
 'moment': 162,
 'quite': 163,
 'felt': 164,
 'girl': 165,
 'left': 166,
 'old': 167,
 'having': 168,
 'seemed': 169,
 'myself': 170,
 'night': 171,
 'however': 172,
 'head': 173,
 'give': 174,
 'place': 175,
 'towards': 176,
 'family': 177,
 'half': 178,
 'many': 179,
 'yet': 180,
 'friend': 181,
 'father': 182,
 'mother': 183,
 'wickham': 184,
 'found': 185,
 'replied': 186,
 'collins': 187,
 'each': 188,
 'even': 189,
 'take': 190,
 'going': 191,
 'under': 192,
 'hope': 193,
 'hand': 194,
 'face': 195,
 'look': 196,
 'tell': 197,
 'de': 198,
 'through': 199,
 'seen': 200,
 'eyes': 201,
 'whom': 202,
 'sure': 203,
 'far': 204,
 'both': 205,
 'better': 206,
 'cannot': 207,
 'enough': 208,
 'same': 209,
 'began': 210,
 'took': 211,
 'three': 212,
 'something': 213,
 'till': 214,
 'side': 215,
 'coming': 216,
 'often': 217,
 'put': 218,
 'perhaps': 219,
 'letter': 220,
 'gone': 221,
 'passed': 222,
 'love': 223,
 'wish': 224,
 'indeed': 225,
 'anything': 226,
 'done': 227,
 'home': 228,
 'lydia': 229,
 'end': 230,
 'few': 231,
 'let': 232,
 'asked': 233,
 'between': 234,
 'rather': 235,
 'looking': 236,
 'those': 237,
 'others': 238,
 'yes': 239,
 'happy': 240,
 'round': 241,
 'whole': 242,
 'against': 243,
 'pleasure': 244,
 'people': 245,
 'near': 246,
 'cried': 247,
 'believe': 248,
 'knew': 249,
 'woman': 250,
 'find': 251,
 'does': 252,
 'really': 253,
 'manner': 254,
 'because': 255,
 'hear': 256,
 'oh': 257,
 'life': 258,
 'catherine': 259,
 'get': 260,
 'almost': 261,
 'nor': 262,
 'light': 263,
 'next': 264,
 'turned': 265,
 'why': 266,
 'upon': 267,
 'another': 268,
 'window': 269,
 'road': 270,
 'gave': 271,
 'sat': 272,
 'called': 273,
 'got': 274,
 'told': 275,
 'longer': 276,
 'happiness': 277,
 'alone': 278,
 'world': 279,
 'voice': 280,
 'everything': 281,
 'together': 282,
 'since': 283,
 'sir': 284,
 'm': 285,
 'children': 286,
 'mind': 287,
 'heart': 288,
 'kind': 289,
 'during': 290,
 'whose': 291,
 'leave': 292,
 'girls': 293,
 'aunt': 294,
 'small': 295,
 'less': 296,
 'feelings': 297,
 'days': 298,
 'answer': 299,
 'speak': 300,
 'ill': 301,
 'certainly': 302,
 'close': 303,
 'galais': 304,
 'subject': 305,
 'lizzy': 306,
 'part': 307,
 'school': 308,
 'suddenly': 309,
 'walk': 310,
 'added': 311,
 'new': 312,
 'already': 313,
 'walked': 314,
 'bessie': 315,
 'right': 316,
 'table': 317,
 'silence': 318,
 'least': 319,
 'country': 320,
 'ladies': 321,
 'word': 322,
 'sometimes': 323,
 'full': 324,
 'daughter': 325,
 'town': 326,
 'attention': 327,
 'lost': 328,
 'continued': 329,
 'longbourn': 330,
 'thus': 331,
 'received': 332,
 'brought': 333,
 'gardiner': 334,
 'poor': 335,
 'set': 336,
 'open': 337,
 'brother': 338,
 'behind': 339,
 'child': 340,
 'present': 341,
 'appeared': 342,
 'hour': 343,
 'immediately': 344,
 'either': 345,
 'uncle': 346,
 'thing': 347,
 'scarcely': 348,
 'carriage': 349,
 'reed': 350,
 'taken': 351,
 'friends': 352,
 'four': 353,
 'spoke': 354,
 'read': 355,
 'given': 356,
 'character': 357,
 'years': 358,
 'returned': 359,
 'strange': 360,
 'stood': 361,
 'dinner': 362,
 'conversation': 363,
 'feel': 364,
 'followed': 365,
 'return': 366,
 'fine': 367,
 'chapter': 368,
 'therefore': 369,
 'sisters': 370,
 'big': 371,
 'things': 372,
 'able': 373,
 'cold': 374,
 'fire': 375,
 'else': 376,
 'used': 377,
 'high': 378,
 'seeing': 379,
 'certain': 380,
 'opinion': 381,
 'want': 382,
 'idea': 383,
 'opened': 384,
 'doubt': 385,
 'course': 386,
 'saying': 387,
 'whether': 388,
 'married': 389,
 'village': 390,
 'front': 391,
 'low': 392,
 'known': 393,
 'name': 394,
 'charlotte': 395,
 'also': 396,
 'making': 397,
 'kept': 398,
 'feeling': 399,
 'ought': 400,
 'person': 401,
 'sort': 402,
 'wife': 403,
 'netherfield': 404,
 'tall': 405,
 'along': 406,
 'wind': 407,
 'call': 408,
 'garden': 409,
 'bed': 410,
 'turn': 411,
 'words': 412,
 'suppose': 413,
 'ask': 414,
 'air': 415,
 'best': 416,
 'means': 417,
 'marriage': 418,
 'hands': 419,
 'stopped': 420,
 'short': 421,
 'dark': 422,
 'silent': 423,
 'keep': 424,
 'entered': 425,
 'large': 426,
 'help': 427,
 'kitty': 428,
 'colonel': 429,
 'men': 430,
 'wood': 431,
 'settled': 432,
 'boys': 433,
 'affection': 434,
 'remained': 435,
 'party': 436,
 'possible': 437,
 'hardly': 438,
 'yourself': 439,
 'lucas': 440,
 'care': 441,
 "'i": 442,
 "don't": 443,
 'likely': 444,
 'talk': 445,
 'minutes': 446,
 'wished': 447,
 'fear': 448,
 'talking': 449,
 'reason': 450,
 'london': 451,
 'winter': 452,
 'rest': 453,
 'work': 454,
 'wanted': 455,
 'visit': 456,
 'point': 457,
 'seurel': 458,
 'five': 459,
 'black': 460,
 'hair': 461,
 'white': 462,
 'general': 463,
 'helen': 464,
 'hall': 465,
 'afraid': 466,
 'within': 467,
 'temple': 468,
 'behaviour': 469,
 'red': 470,
 'sand': 471,
 'usual': 472,
 'reached': 473,
 'pride': 474,
 'book': 475,
 'acquaintance': 476,
 'perfectly': 477,
 'answered': 478,
 'second': 479,
 'matter': 480,
 'met': 481,
 'dare': 482,
 'glad': 483,
 'neither': 484,
 'women': 485,
 'ten': 486,
 'above': 487,
 'expected': 488,
 'remember': 489,
 'live': 490,
 'daughters': 491,
 'object': 492,
 'pemberley': 493,
 'meet': 494,
 'reply': 495,
 'meryton': 496,
 'gate': 497,
 'surprise': 498,
 'liked': 499,
 'news': 500,
 'tried': 501,
 'handsome': 502,
 'stay': 503,
 'business': 504,
 'themselves': 505,
 'cart': 506,
 'early': 507,
 'dining': 508,
 'amongst': 509,
 'steps': 510,
 'master': 511,
 'beautiful': 512,
 'engaged': 513,
 'husband': 514,
 'speaking': 515,
 'street': 516,
 'anxious': 517,
 'year': 518,
 'talked': 519,
 'pleased': 520,
 'regard': 521,
 'rosings': 522,
 'understand': 523,
 'impossible': 524,
 'marry': 525,
 'account': 526,
 'agreeable': 527,
 "bingley's": 528,
 'breakfast': 529,
 'brocklehurst': 530,
 'ago': 531,
 'journey': 532,
 'church': 533,
 'afternoon': 534,
 'taking': 535,
 'fellow': 536,
 'question': 537,
 'drawing': 538,
 'write': 539,
 'sent': 540,
 'happened': 541,
 'everybody': 542,
 'obliged': 543,
 'believed': 544,
 'surprised': 545,
 'sense': 546,
 'different': 547,
 'manners': 548,
 'sitting': 549,
 'ready': 550,
 'smile': 551,
 'jasmin': 552,
 'wonder': 553,
 'convinced': 554,
 'distance': 555,
 'eye': 556,
 'spirits': 557,
 'beyond': 558,
 'late': 559,
 'forward': 560,
 'doing': 561,
 'became': 562,
 'walking': 563,
 'delouche': 564,
 'former': 565,
 'afterwards': 566,
 'power': 567,
 'summer': 568,
 'caught': 569,
 'pretty': 570,
 'times': 571,
 'easy': 572,
 'slowly': 573,
 'ran': 574,
 'past': 575,
 'frantz': 576,
 'mean': 577,
 'situation': 578,
 'fairfax': 579,
 'windows': 580,
 'arrival': 581,
 'week': 582,
 'standing': 583,
 'spite': 584,
 'listened': 585,
 'necessary': 586,
 'cousin': 587,
 'assure': 588,
 'occasion': 589,
 'deal': 590,
 "darcy's": 591,
 'led': 592,
 'thoughts': 593,
 'thinking': 594,
 "'you": 595,
 'hours': 596,
 'manor': 597,
 'civility': 598,
 'spent': 599,
 'arm': 600,
 'boy': 601,
 'allowed': 602,
 'leaving': 603,
 'admiral': 604,
 'clear': 605,
 'adventure': 606,
 'books': 607,
 'fair': 608,
 'says': 609,
 'appearance': 610,
 'neighbourhood': 611,
 'meant': 612,
 'change': 613,
 'exactly': 614,
 'gentlemen': 615,
 'knowing': 616,
 'nature': 617,
 'pit': 618,
 'instantly': 619,
 'mary': 620,
 'honour': 621,
 'hertfordshire': 622,
 'playground': 623,
 'younger': 624,
 "o'clock": 625,
 'length': 626,
 'notice': 627,
 'lane': 628,
 'play': 629,
 'top': 630,
 'horse': 631,
 'interest': 632,
 'gentleman': 633,
 'appear': 634,
 'bad': 635,
 'turning': 636,
 'ground': 637,
 'rain': 638,
 'form': 639,
 'morrow': 640,
 'seated': 641,
 'hard': 642,
 'wait': 643,
 'several': 644,
 'probably': 645,
 'clothes': 646,
 'besides': 647,
 'rose': 648,
 'truth': 649,
 'resolved': 650,
 'expect': 651,
 'case': 652,
 'fortune': 653,
 'william': 654,
 'amiable': 655,
 'lowood': 656,
 'doors': 657,
 'bring': 658,
 'trees': 659,
 'heavy': 660,
 'fact': 661,
 'step': 662,
 'tired': 663,
 'augustin': 664,
 'dead': 665,
 'real': 666,
 'seems': 667,
 'placed': 668,
 'struck': 669,
 'pale': 670,
 'whatever': 671,
 'beauty': 672,
 'money': 673,
 'sorry': 674,
 "lydia's": 675,
 'nearly': 676,
 'waiting': 677,
 'show': 678,
 'arms': 679,
 'feet': 680,
 'son': 681,
 'water': 682,
 'seat': 683,
 'send': 684,
 'mine': 685,
 'dance': 686,
 'sit': 687,
 'true': 688,
 'sound': 689,
 'vain': 690,
 'ball': 691,
 'except': 692,
 'among': 693,
 'wishes': 694,
 'kindness': 695,
 'allow': 696,
 'satisfied': 697,
 "elizabeth's": 698,
 'forster': 699,
 "sister's": 700,
 'living': 701,
 'rooms': 702,
 'imagine': 703,
 'dared': 704,
 'run': 705,
 'mysterious': 706,
 'farm': 707,
 'candle': 708,
 'companion': 709,
 'comes': 710,
 'following': 711,
 'giving': 712,
 'path': 713,
 'pain': 714,
 'delight': 715,
 'observed': 716,
 'sensible': 717,
 'age': 718,
 'offer': 719,
 'merely': 720,
 'society': 721,
 'quiet': 722,
 'shut': 723,
 'anxiety': 724,
 'stand': 725,
 'unknown': 726,
 'noise': 727,
 'yard': 728,
 'hold': 729,
 'drew': 730,
 'strong': 731,
 'noticed': 732,
 'closed': 733,
 'shoes': 734,
 'wedding': 735,
 'mademoiselle': 736,
 'thousand': 737,
 'pleasant': 738,
 'bear': 739,
 'advantage': 740,
 'bourgh': 741,
 'wall': 742,
 'smiled': 743,
 'watched': 744,
 'beginning': 745,
 'fell': 746,
 'curiosity': 747,
 'deep': 748,
 'broken': 749,
 'finished': 750,
 'foot': 751,
 'chair': 752,
 "mother's": 753,
 'forced': 754,
 'servant': 755,
 'charming': 756,
 'pass': 757,
 'lived': 758,
 'invitation': 759,
 'mentioned': 760,
 'opportunity': 761,
 'expressed': 762,
 'trouble': 763,
 'consider': 764,
 'comfort': 765,
 'grey': 766,
 'hearing': 767,
 'held': 768,
 'astonishment': 769,
 'story': 770,
 'laugh': 771,
 'repeated': 772,
 'farther': 773,
 'state': 774,
 'dress': 775,
 'regret': 776,
 'bell': 777,
 'whenever': 778,
 'equal': 779,
 'death': 780,
 'circumstances': 781,
 'countenance': 782,
 'considered': 783,
 'respect': 784,
 'mention': 785,
 'particularly': 786,
 'consequence': 787,
 'arrived': 788,
 'follow': 789,
 'fall': 790,
 'sight': 791,
 'scene': 792,
 'decided': 793,
 'stairs': 794,
 'eight': 795,
 'across': 796,
 'entirely': 797,
 'view': 798,
 'absence': 799,
 'cross': 800,
 'questions': 801,
 'none': 802,
 'promise': 803,
 'instead': 804,
 'directly': 805,
 'ease': 806,
 'joined': 807,
 'serious': 808,
 'chance': 809,
 'letters': 810,
 'hurst': 811,
 'eliza': 812,
 'madam': 813,
 "wickham's": 814,
 'fitzwilliam': 815,
 'glass': 816,
 'admiration': 817,
 'entrance': 818,
 'fixed': 819,
 'generally': 820,
 'assured': 821,
 'asleep': 822,
 'self': 823,
 'desire': 824,
 'dressed': 825,
 'easily': 826,
 'started': 827,
 'fancy': 828,
 'tears': 829,
 'information': 830,
 'natural': 831,
 'particular': 832,
 'plan': 833,
 'kitchen': 834,
 'classroom': 835,
 'extraordinary': 836,
 'month': 837,
 'hurried': 838,
 'address': 839,
 'temper': 840,
 'lay': 841,
 'secret': 842,
 'running': 843,
 'yvonne': 844,
 'order': 845,
 'satisfaction': 846,
 'determined': 847,
 'degree': 848,
 'ladyship': 849,
 'picture': 850,
 'getting': 851,
 'square': 852,
 'tone': 853,
 'hopes': 854,
 'shop': 855,
 'class': 856,
 'cloak': 857,
 'begin': 858,
 'hill': 859,
 'twice': 860,
 'passing': 861,
 'written': 862,
 'wrote': 863,
 'months': 864,
 'supposed': 865,
 'further': 866,
 'company': 867,
 'officers': 868,
 'disposition': 869,
 'receive': 870,
 'sainte': 871,
 'opening': 872,
 'agathe': 873,
 'proud': 874,
 'removed': 875,
 'miles': 876,
 'narrow': 877,
 'fetch': 878,
 'become': 879,
 'sleep': 880,
 'meeting': 881,
 'spoken': 882,
 'match': 883,
 'shook': 884,
 'prevented': 885,
 'thursday': 886,
 'library': 887,
 'greater': 888,
 'credit': 889,
 'highly': 890,
 'pounds': 891,
 'importance': 892,
 'attachment': 893,
 'pray': 894,
 'relations': 895,
 'especially': 896,
 'frequently': 897,
 'tea': 898,
 'burns': 899,
 'millie': 900,
 'youth': 901,
 'until': 902,
 'mistaken': 903,
 'please': 904,
 'wild': 905,
 'darkness': 906,
 'showed': 907,
 'wretched': 908,
 'marked': 909,
 'calling': 910,
 'voices': 911,
 'event': 912,
 'need': 913,
 'wide': 914,
 'understood': 915,
 'related': 916,
 'taste': 917,
 'estate': 918,
 'covered': 919,
 'listen': 920,
 'six': 921,
 'asking': 922,
 'sad': 923,
 'concern': 924,
 'intended': 925,
 'valentine': 926,
 'pleasing': 927,
 'promised': 928,
 'express': 929,
 'dislike': 930,
 'anybody': 931,
 'conduct': 932,
 'georgiana': 933,
 'john': 934,
 'eyre': 935,
 'gateshead': 936,
 'middle': 937,
 'walls': 938,
 'leading': 939,
 'station': 940,
 'hat': 941,
 'quickly': 942,
 'praise': 943,
 'attempt': 944,
 'raised': 945,
 'offered': 946,
 'distress': 947,
 'fortnight': 948,
 'latter': 949,
 'formed': 950,
 'empty': 951,
 'quietly': 952,
 'bohemian': 953,
 'acquainted': 954,
 'park': 955,
 'addressed': 956,
 "bennet's": 957,
 "jane's": 958,
 'compliment': 959,
 'exceedingly': 960,
 'building': 961,
 'gently': 962,
 'listening': 963,
 'smiling': 964,
 'bread': 965,
 'writing': 966,
 'pupil': 967,
 'teachers': 968,
 'avoid': 969,
 'joy': 970,
 'delighted': 971,
 'forgotten': 972,
 'stranger': 973,
 "'and": 974,
 'inquiries': 975,
 'persuaded': 976,
 'inclination': 977,
 'forget': 978,
 'gratitude': 979,
 'sake': 980,
 'humour': 981,
 'excellent': 982,
 'circumstance': 983,
 'favour': 984,
 'attentions': 985,
 'attended': 986,
 'phillips': 987,
 'wholly': 988,
 'hunsford': 989,
 'try': 990,
 'shoulders': 991,
 'putting': 992,
 "meaulnes'": 993,
 'stop': 994,
 'madame': 995,
 'wrong': 996,
 'ended': 997,
 'direction': 998,
 "it's": 999,
 "i've": 1000,
 ...}

In [ ]:
target_vocab_size

17739

In [ ]:

# Step 4: Define transformer model
class Transformer(tf.keras.Model):
    def __init__(self, input_vocab, target_vocab, d_model, num_heads, dff, pe_input, pe_target):
        super().__init__()
        self.encoder_embedding = tf.keras.layers.Embedding(input_vocab, d_model)
        self.decoder_embedding = tf.keras.layers.Embedding(target_vocab, d_model)
        self.pos_encoding_input = self.positional_encoding(pe_input, d_model)
        self.pos_encoding_target = self.positional_encoding(pe_target, d_model)

        self.enc_layer = tf.keras.layers.MultiHeadAttention(num_heads=num_heads, key_dim=d_model)
        self.dec_layer = tf.keras.layers.MultiHeadAttention(num_heads=num_heads, key_dim=d_model)
        self.dense_proj = tf.keras.Sequential([
            tf.keras.layers.Dense(dff, activation='relu'),
            tf.keras.layers.Dense(d_model)
        ])
        self.final_dense = tf.keras.layers.Dense(target_vocab)

    def positional_encoding(self, max_len, dm):
        pos = np.arange(max_len)[:, np.newaxis]
        i = np.arange(dm)[np.newaxis, :]
        angle_rates = 1 / np.power(10000, (2 * (i//2)) / np.float32(dm))
        angle_rads = pos * angle_rates
        angle_rads[:, 0::2] = np.sin(angle_rads[:, 0::2])
        angle_rads[:, 1::2] = np.cos(angle_rads[:, 1::2])
        return tf.cast(angle_rads, dtype=tf.float32)

    def call(self, inputs, training=False):
        inp, tar = inputs
        enc = self.encoder_embedding(inp) + self.pos_encoding_input[:tf.shape(inp)[1]]
        dec = self.decoder_embedding(tar) + self.pos_encoding_target[:tf.shape(tar)[1]]
        enc_output = self.enc_layer(enc, enc)
        dec_output = self.dec_layer(dec, enc_output)
        final = self.dense_proj(dec_output)
        return self.final_dense(final)

In [ ]:
en_tensor.shape

(10000, 40)

In [ ]:

# Step 5: Compile and train
model = Transformer(input_vocab=input_vocab_size, target_vocab=target_vocab_size,
                    d_model=64, num_heads=4, dff=128, pe_input=en_tensor.shape[1], pe_target=fr_tensor.shape[1])
model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])
model.fit([en_tensor, fr_tensor[:, :-1]], fr_tensor[:, 1:], epochs=100, batch_size=32)

Epoch 1/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 14s 22ms/step - accuracy: 0.4581 - loss: 4.9592
Epoch 2/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.4837 - loss: 3.4979
Epoch 3/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.5183 - loss: 3.2659
Epoch 4/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.5211 - loss: 3.1655
Epoch 5/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.5289 - loss: 3.0185
Epoch 6/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.5292 - loss: 2.9383
Epoch 7/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.5403 - loss: 2.8134
Epoch 8/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.5407 - loss: 2.7634
Epoch 9/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.5445 - loss: 2.7079
Epoch 10/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - accuracy: 0.5495 - loss: 2.6482
Epoch 11/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - accuracy: 0.5436 - loss: 2.6511
Epoch 12/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 4s 14ms/step - accuracy: 0.5497 - loss: 2.5840
Epoch 13/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - accuracy: 0.5574 - loss: 2.5184
Epoch 14/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - accuracy: 0.5524 - loss: 2.5229
Epoch 15/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - accuracy: 0.5546 - loss: 2.4841
Epoch 16/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.5533 - loss: 2.4627
Epoch 17/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.5558 - loss: 2.4310
Epoch 18/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.5601 - loss: 2.3880
Epoch 19/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.5626 - loss: 2.3510
Epoch 20/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.5654 - loss: 2.3152
Epoch 21/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.5668 - loss: 2.2921
Epoch 22/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.5643 - loss: 2.2882
Epoch 23/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.5621 - loss: 2.2796
Epoch 24/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.5647 - loss: 2.2524
Epoch 25/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.5687 - loss: 2.2180
Epoch 26/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.5690 - loss: 2.2035
Epoch 27/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.5677 - loss: 2.1926
Epoch 28/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.5716 - loss: 2.1631
Epoch 29/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.5729 - loss: 2.1405
Epoch 30/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.5798 - loss: 2.0961
Epoch 31/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.5791 - loss: 2.0833
Epoch 32/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.5803 - loss: 2.0693
Epoch 33/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.5812 - loss: 2.0487
Epoch 34/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.5858 - loss: 2.0167
Epoch 35/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.5861 - loss: 2.0043
Epoch 36/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - accuracy: 0.5878 - loss: 1.9957
Epoch 37/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.5916 - loss: 1.9640
Epoch 38/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - accuracy: 0.5883 - loss: 1.9742
Epoch 39/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - accuracy: 0.5986 - loss: 1.9151
Epoch 40/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - accuracy: 0.5959 - loss: 1.9181
Epoch 41/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.6031 - loss: 1.8752
Epoch 42/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.6006 - loss: 1.8851
Epoch 43/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.6040 - loss: 1.8614
Epoch 44/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.6068 - loss: 1.8401
Epoch 45/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.6073 - loss: 1.8370
Epoch 46/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.6140 - loss: 1.8000
Epoch 47/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.6174 - loss: 1.7786
Epoch 48/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.6188 - loss: 1.7667
Epoch 49/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - accuracy: 0.6191 - loss: 1.7633
Epoch 50/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.6124 - loss: 1.7870
Epoch 51/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.6266 - loss: 1.7165
Epoch 52/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.6264 - loss: 1.7097
Epoch 53/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.6276 - loss: 1.7003
Epoch 54/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.6339 - loss: 1.6708
Epoch 55/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.6318 - loss: 1.6752
Epoch 56/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.6346 - loss: 1.6558
Epoch 57/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.6350 - loss: 1.6538
Epoch 58/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.6379 - loss: 1.6386
Epoch 59/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.6394 - loss: 1.6284
Epoch 60/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.6396 - loss: 1.6219
Epoch 61/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.6438 - loss: 1.6029
Epoch 62/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.6481 - loss: 1.5807
Epoch 63/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.6451 - loss: 1.5867
Epoch 64/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.6532 - loss: 1.5515
Epoch 65/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.6484 - loss: 1.5703
Epoch 66/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.6547 - loss: 1.5362
Epoch 67/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.6550 - loss: 1.5316
Epoch 68/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.6575 - loss: 1.5216
Epoch 69/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.6592 - loss: 1.5090
Epoch 70/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.6653 - loss: 1.4780
Epoch 71/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.6655 - loss: 1.4751
Epoch 72/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.6673 - loss: 1.4677
Epoch 73/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.6717 - loss: 1.4426
Epoch 74/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.6712 - loss: 1.4444
Epoch 75/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - accuracy: 0.6737 - loss: 1.4325
Epoch 76/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.6759 - loss: 1.4179
Epoch 77/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.6741 - loss: 1.4230
Epoch 78/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.6739 - loss: 1.4286
Epoch 79/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.6790 - loss: 1.3960
Epoch 80/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.6791 - loss: 1.3949
Epoch 81/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.6851 - loss: 1.3678
Epoch 82/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.6846 - loss: 1.3681
Epoch 83/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.6822 - loss: 1.3796
Epoch 84/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.6854 - loss: 1.3600
Epoch 85/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.6857 - loss: 1.3547
Epoch 86/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - accuracy: 0.6879 - loss: 1.3410
Epoch 87/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.6935 - loss: 1.3213
Epoch 88/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.6926 - loss: 1.3237
Epoch 89/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - accuracy: 0.6963 - loss: 1.3039
Epoch 90/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.6964 - loss: 1.2984
Epoch 91/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.6972 - loss: 1.2973
Epoch 92/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - accuracy: 0.7011 - loss: 1.2791
Epoch 93/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.7004 - loss: 1.2797
Epoch 94/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.7050 - loss: 1.2562
Epoch 95/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.7056 - loss: 1.2541
Epoch 96/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.7037 - loss: 1.2582
Epoch 97/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.7096 - loss: 1.2333
Epoch 98/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.7046 - loss: 1.2498
Epoch 99/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.7105 - loss: 1.2256
Epoch 100/100
313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.7104 - loss: 1.2232

In [ ]:
fr_tensor.shape

(10000, 40)

In [ ]:
en_tokenizer.word_index

{'<OOV>': 1,
 'the': 2,
 'to': 3,
 'and': 4,
 'of': 5,
 'i': 6,
 'a': 7,
 'in': 8,
 'was': 9,
 'her': 10,
 'he': 11,
 'she': 12,
 'it': 13,
 'that': 14,
 'had': 15,
 'his': 16,
 'not': 17,
 'you': 18,
 'with': 19,
 'as': 20,
 'at': 21,
 'for': 22,
 'on': 23,
 'be': 24,
 'my': 25,
 'but': 26,
 'is': 27,
 'me': 28,
 'have': 29,
 'him': 30,
 'by': 31,
 'which': 32,
 'all': 33,
 'from': 34,
 'were': 35,
 'so': 36,
 'this': 37,
 'they': 38,
 'mr': 39,
 'could': 40,
 'no': 41,
 'been': 42,
 'one': 43,
 'what': 44,
 'would': 45,
 'said': 46,
 'when': 47,
 'we': 48,
 'very': 49,
 "'": 50,
 'there': 51,
 'an': 52,
 'their': 53,
 'them': 54,
 'your': 55,
 'elizabeth': 56,
 'or': 57,
 'who': 58,
 'if': 59,
 'are': 60,
 'will': 61,
 'then': 62,
 'more': 63,
 'do': 64,
 'little': 65,
 'up': 66,
 'out': 67,
 'such': 68,
 'now': 69,
 'must': 70,
 'miss': 71,
 'mrs': 72,
 'time': 73,
 'some': 74,
 'much': 75,
 'am': 76,
 'did': 77,
 'only': 78,
 'than': 79,
 'before': 80,
 'room': 81,
 'darcy': 82,
 'never': 83,
 'any': 84,
 'know': 85,
 'well': 86,
 'other': 87,
 'again': 88,
 'should': 89,
 'meaulnes': 90,
 'like': 91,
 'us': 92,
 'into': 93,
 'how': 94,
 'two': 95,
 'long': 96,
 'after': 97,
 'soon': 98,
 'has': 99,
 'good': 100,
 'jane': 101,
 'first': 102,
 'day': 103,
 'can': 104,
 'see': 105,
 'though': 106,
 'bennet': 107,
 'without': 108,
 'came': 109,
 'back': 110,
 'think': 111,
 'last': 112,
 'too': 113,
 'where': 114,
 'come': 115,
 'go': 116,
 'every': 117,
 'about': 118,
 'most': 119,
 'over': 120,
 'say': 121,
 'might': 122,
 'herself': 123,
 'nothing': 124,
 'way': 125,
 'house': 126,
 'bingley': 127,
 'went': 128,
 'own': 129,
 'young': 130,
 'down': 131,
 'made': 132,
 'great': 133,
 'man': 134,
 'make': 135,
 'being': 136,
 'shall': 137,
 'thought': 138,
 'our': 139,
 'away': 140,
 'lady': 141,
 'its': 142,
 'himself': 143,
 'may': 144,
 'while': 145,
 'heard': 146,
 'once': 147,
 'door': 148,
 'saw': 149,
 'always': 150,
 'ever': 151,
 'these': 152,
 'looked': 153,
 'still': 154,
 'evening': 155,
 'sister': 156,
 'off': 157,
 'just': 158,
 'morning': 159,
 'here': 160,
 'dear': 161,
 'moment': 162,
 'quite': 163,
 'felt': 164,
 'girl': 165,
 'left': 166,
 'old': 167,
 'having': 168,
 'seemed': 169,
 'myself': 170,
 'night': 171,
 'however': 172,
 'head': 173,
 'give': 174,
 'place': 175,
 'towards': 176,
 'family': 177,
 'half': 178,
 'many': 179,
 'yet': 180,
 'friend': 181,
 'father': 182,
 'mother': 183,
 'wickham': 184,
 'found': 185,
 'replied': 186,
 'collins': 187,
 'each': 188,
 'even': 189,
 'take': 190,
 'going': 191,
 'under': 192,
 'hope': 193,
 'hand': 194,
 'face': 195,
 'look': 196,
 'tell': 197,
 'de': 198,
 'through': 199,
 'seen': 200,
 'eyes': 201,
 'whom': 202,
 'sure': 203,
 'far': 204,
 'both': 205,
 'better': 206,
 'cannot': 207,
 'enough': 208,
 'same': 209,
 'began': 210,
 'took': 211,
 'three': 212,
 'something': 213,
 'till': 214,
 'side': 215,
 'coming': 216,
 'often': 217,
 'put': 218,
 'perhaps': 219,
 'letter': 220,
 'gone': 221,
 'passed': 222,
 'love': 223,
 'wish': 224,
 'indeed': 225,
 'anything': 226,
 'done': 227,
 'home': 228,
 'lydia': 229,
 'end': 230,
 'few': 231,
 'let': 232,
 'asked': 233,
 'between': 234,
 'rather': 235,
 'looking': 236,
 'those': 237,
 'others': 238,
 'yes': 239,
 'happy': 240,
 'round': 241,
 'whole': 242,
 'against': 243,
 'pleasure': 244,
 'people': 245,
 'near': 246,
 'cried': 247,
 'believe': 248,
 'knew': 249,
 'woman': 250,
 'find': 251,
 'does': 252,
 'really': 253,
 'manner': 254,
 'because': 255,
 'hear': 256,
 'oh': 257,
 'life': 258,
 'catherine': 259,
 'get': 260,
 'almost': 261,
 'nor': 262,
 'light': 263,
 'next': 264,
 'turned': 265,
 'why': 266,
 'upon': 267,
 'another': 268,
 'window': 269,
 'road': 270,
 'gave': 271,
 'sat': 272,
 'called': 273,
 'got': 274,
 'told': 275,
 'longer': 276,
 'happiness': 277,
 'alone': 278,
 'world': 279,
 'voice': 280,
 'everything': 281,
 'together': 282,
 'since': 283,
 'sir': 284,
 'm': 285,
 'children': 286,
 'mind': 287,
 'heart': 288,
 'kind': 289,
 'during': 290,
 'whose': 291,
 'leave': 292,
 'girls': 293,
 'aunt': 294,
 'small': 295,
 'less': 296,
 'feelings': 297,
 'days': 298,
 'answer': 299,
 'speak': 300,
 'ill': 301,
 'certainly': 302,
 'close': 303,
 'galais': 304,
 'subject': 305,
 'lizzy': 306,
 'part': 307,
 'school': 308,
 'suddenly': 309,
 'walk': 310,
 'added': 311,
 'new': 312,
 'already': 313,
 'walked': 314,
 'bessie': 315,
 'right': 316,
 'table': 317,
 'silence': 318,
 'least': 319,
 'country': 320,
 'ladies': 321,
 'word': 322,
 'sometimes': 323,
 'full': 324,
 'daughter': 325,
 'town': 326,
 'attention': 327,
 'lost': 328,
 'continued': 329,
 'longbourn': 330,
 'thus': 331,
 'received': 332,
 'brought': 333,
 'gardiner': 334,
 'poor': 335,
 'set': 336,
 'open': 337,
 'brother': 338,
 'behind': 339,
 'child': 340,
 'present': 341,
 'appeared': 342,
 'hour': 343,
 'immediately': 344,
 'either': 345,
 'uncle': 346,
 'thing': 347,
 'scarcely': 348,
 'carriage': 349,
 'reed': 350,
 'taken': 351,
 'friends': 352,
 'four': 353,
 'spoke': 354,
 'read': 355,
 'given': 356,
 'character': 357,
 'years': 358,
 'returned': 359,
 'strange': 360,
 'stood': 361,
 'dinner': 362,
 'conversation': 363,
 'feel': 364,
 'followed': 365,
 'return': 366,
 'fine': 367,
 'chapter': 368,
 'therefore': 369,
 'sisters': 370,
 'big': 371,
 'things': 372,
 'able': 373,
 'cold': 374,
 'fire': 375,
 'else': 376,
 'used': 377,
 'high': 378,
 'seeing': 379,
 'certain': 380,
 'opinion': 381,
 'want': 382,
 'idea': 383,
 'opened': 384,
 'doubt': 385,
 'course': 386,
 'saying': 387,
 'whether': 388,
 'married': 389,
 'village': 390,
 'front': 391,
 'low': 392,
 'known': 393,
 'name': 394,
 'charlotte': 395,
 'also': 396,
 'making': 397,
 'kept': 398,
 'feeling': 399,
 'ought': 400,
 'person': 401,
 'sort': 402,
 'wife': 403,
 'netherfield': 404,
 'tall': 405,
 'along': 406,
 'wind': 407,
 'call': 408,
 'garden': 409,
 'bed': 410,
 'turn': 411,
 'words': 412,
 'suppose': 413,
 'ask': 414,
 'air': 415,
 'best': 416,
 'means': 417,
 'marriage': 418,
 'hands': 419,
 'stopped': 420,
 'short': 421,
 'dark': 422,
 'silent': 423,
 'keep': 424,
 'entered': 425,
 'large': 426,
 'help': 427,
 'kitty': 428,
 'colonel': 429,
 'men': 430,
 'wood': 431,
 'settled': 432,
 'boys': 433,
 'affection': 434,
 'remained': 435,
 'party': 436,
 'possible': 437,
 'hardly': 438,
 'yourself': 439,
 'lucas': 440,
 'care': 441,
 "'i": 442,
 "don't": 443,
 'likely': 444,
 'talk': 445,
 'minutes': 446,
 'wished': 447,
 'fear': 448,
 'talking': 449,
 'reason': 450,
 'london': 451,
 'winter': 452,
 'rest': 453,
 'work': 454,
 'wanted': 455,
 'visit': 456,
 'point': 457,
 'seurel': 458,
 'five': 459,
 'black': 460,
 'hair': 461,
 'white': 462,
 'general': 463,
 'helen': 464,
 'hall': 465,
 'afraid': 466,
 'within': 467,
 'temple': 468,
 'behaviour': 469,
 'red': 470,
 'sand': 471,
 'usual': 472,
 'reached': 473,
 'pride': 474,
 'book': 475,
 'acquaintance': 476,
 'perfectly': 477,
 'answered': 478,
 'second': 479,
 'matter': 480,
 'met': 481,
 'dare': 482,
 'glad': 483,
 'neither': 484,
 'women': 485,
 'ten': 486,
 'above': 487,
 'expected': 488,
 'remember': 489,
 'live': 490,
 'daughters': 491,
 'object': 492,
 'pemberley': 493,
 'meet': 494,
 'reply': 495,
 'meryton': 496,
 'gate': 497,
 'surprise': 498,
 'liked': 499,
 'news': 500,
 'tried': 501,
 'handsome': 502,
 'stay': 503,
 'business': 504,
 'themselves': 505,
 'cart': 506,
 'early': 507,
 'dining': 508,
 'amongst': 509,
 'steps': 510,
 'master': 511,
 'beautiful': 512,
 'engaged': 513,
 'husband': 514,
 'speaking': 515,
 'street': 516,
 'anxious': 517,
 'year': 518,
 'talked': 519,
 'pleased': 520,
 'regard': 521,
 'rosings': 522,
 'understand': 523,
 'impossible': 524,
 'marry': 525,
 'account': 526,
 'agreeable': 527,
 "bingley's": 528,
 'breakfast': 529,
 'brocklehurst': 530,
 'ago': 531,
 'journey': 532,
 'church': 533,
 'afternoon': 534,
 'taking': 535,
 'fellow': 536,
 'question': 537,
 'drawing': 538,
 'write': 539,
 'sent': 540,
 'happened': 541,
 'everybody': 542,
 'obliged': 543,
 'believed': 544,
 'surprised': 545,
 'sense': 546,
 'different': 547,
 'manners': 548,
 'sitting': 549,
 'ready': 550,
 'smile': 551,
 'jasmin': 552,
 'wonder': 553,
 'convinced': 554,
 'distance': 555,
 'eye': 556,
 'spirits': 557,
 'beyond': 558,
 'late': 559,
 'forward': 560,
 'doing': 561,
 'became': 562,
 'walking': 563,
 'delouche': 564,
 'former': 565,
 'afterwards': 566,
 'power': 567,
 'summer': 568,
 'caught': 569,
 'pretty': 570,
 'times': 571,
 'easy': 572,
 'slowly': 573,
 'ran': 574,
 'past': 575,
 'frantz': 576,
 'mean': 577,
 'situation': 578,
 'fairfax': 579,
 'windows': 580,
 'arrival': 581,
 'week': 582,
 'standing': 583,
 'spite': 584,
 'listened': 585,
 'necessary': 586,
 'cousin': 587,
 'assure': 588,
 'occasion': 589,
 'deal': 590,
 "darcy's": 591,
 'led': 592,
 'thoughts': 593,
 'thinking': 594,
 "'you": 595,
 'hours': 596,
 'manor': 597,
 'civility': 598,
 'spent': 599,
 'arm': 600,
 'boy': 601,
 'allowed': 602,
 'leaving': 603,
 'admiral': 604,
 'clear': 605,
 'adventure': 606,
 'books': 607,
 'fair': 608,
 'says': 609,
 'appearance': 610,
 'neighbourhood': 611,
 'meant': 612,
 'change': 613,
 'exactly': 614,
 'gentlemen': 615,
 'knowing': 616,
 'nature': 617,
 'pit': 618,
 'instantly': 619,
 'mary': 620,
 'honour': 621,
 'hertfordshire': 622,
 'playground': 623,
 'younger': 624,
 "o'clock": 625,
 'length': 626,
 'notice': 627,
 'lane': 628,
 'play': 629,
 'top': 630,
 'horse': 631,
 'interest': 632,
 'gentleman': 633,
 'appear': 634,
 'bad': 635,
 'turning': 636,
 'ground': 637,
 'rain': 638,
 'form': 639,
 'morrow': 640,
 'seated': 641,
 'hard': 642,
 'wait': 643,
 'several': 644,
 'probably': 645,
 'clothes': 646,
 'besides': 647,
 'rose': 648,
 'truth': 649,
 'resolved': 650,
 'expect': 651,
 'case': 652,
 'fortune': 653,
 'william': 654,
 'amiable': 655,
 'lowood': 656,
 'doors': 657,
 'bring': 658,
 'trees': 659,
 'heavy': 660,
 'fact': 661,
 'step': 662,
 'tired': 663,
 'augustin': 664,
 'dead': 665,
 'real': 666,
 'seems': 667,
 'placed': 668,
 'struck': 669,
 'pale': 670,
 'whatever': 671,
 'beauty': 672,
 'money': 673,
 'sorry': 674,
 "lydia's": 675,
 'nearly': 676,
 'waiting': 677,
 'show': 678,
 'arms': 679,
 'feet': 680,
 'son': 681,
 'water': 682,
 'seat': 683,
 'send': 684,
 'mine': 685,
 'dance': 686,
 'sit': 687,
 'true': 688,
 'sound': 689,
 'vain': 690,
 'ball': 691,
 'except': 692,
 'among': 693,
 'wishes': 694,
 'kindness': 695,
 'allow': 696,
 'satisfied': 697,
 "elizabeth's": 698,
 'forster': 699,
 "sister's": 700,
 'living': 701,
 'rooms': 702,
 'imagine': 703,
 'dared': 704,
 'run': 705,
 'mysterious': 706,
 'farm': 707,
 'candle': 708,
 'companion': 709,
 'comes': 710,
 'following': 711,
 'giving': 712,
 'path': 713,
 'pain': 714,
 'delight': 715,
 'observed': 716,
 'sensible': 717,
 'age': 718,
 'offer': 719,
 'merely': 720,
 'society': 721,
 'quiet': 722,
 'shut': 723,
 'anxiety': 724,
 'stand': 725,
 'unknown': 726,
 'noise': 727,
 'yard': 728,
 'hold': 729,
 'drew': 730,
 'strong': 731,
 'noticed': 732,
 'closed': 733,
 'shoes': 734,
 'wedding': 735,
 'mademoiselle': 736,
 'thousand': 737,
 'pleasant': 738,
 'bear': 739,
 'advantage': 740,
 'bourgh': 741,
 'wall': 742,
 'smiled': 743,
 'watched': 744,
 'beginning': 745,
 'fell': 746,
 'curiosity': 747,
 'deep': 748,
 'broken': 749,
 'finished': 750,
 'foot': 751,
 'chair': 752,
 "mother's": 753,
 'forced': 754,
 'servant': 755,
 'charming': 756,
 'pass': 757,
 'lived': 758,
 'invitation': 759,
 'mentioned': 760,
 'opportunity': 761,
 'expressed': 762,
 'trouble': 763,
 'consider': 764,
 'comfort': 765,
 'grey': 766,
 'hearing': 767,
 'held': 768,
 'astonishment': 769,
 'story': 770,
 'laugh': 771,
 'repeated': 772,
 'farther': 773,
 'state': 774,
 'dress': 775,
 'regret': 776,
 'bell': 777,
 'whenever': 778,
 'equal': 779,
 'death': 780,
 'circumstances': 781,
 'countenance': 782,
 'considered': 783,
 'respect': 784,
 'mention': 785,
 'particularly': 786,
 'consequence': 787,
 'arrived': 788,
 'follow': 789,
 'fall': 790,
 'sight': 791,
 'scene': 792,
 'decided': 793,
 'stairs': 794,
 'eight': 795,
 'across': 796,
 'entirely': 797,
 'view': 798,
 'absence': 799,
 'cross': 800,
 'questions': 801,
 'none': 802,
 'promise': 803,
 'instead': 804,
 'directly': 805,
 'ease': 806,
 'joined': 807,
 'serious': 808,
 'chance': 809,
 'letters': 810,
 'hurst': 811,
 'eliza': 812,
 'madam': 813,
 "wickham's": 814,
 'fitzwilliam': 815,
 'glass': 816,
 'admiration': 817,
 'entrance': 818,
 'fixed': 819,
 'generally': 820,
 'assured': 821,
 'asleep': 822,
 'self': 823,
 'desire': 824,
 'dressed': 825,
 'easily': 826,
 'started': 827,
 'fancy': 828,
 'tears': 829,
 'information': 830,
 'natural': 831,
 'particular': 832,
 'plan': 833,
 'kitchen': 834,
 'classroom': 835,
 'extraordinary': 836,
 'month': 837,
 'hurried': 838,
 'address': 839,
 'temper': 840,
 'lay': 841,
 'secret': 842,
 'running': 843,
 'yvonne': 844,
 'order': 845,
 'satisfaction': 846,
 'determined': 847,
 'degree': 848,
 'ladyship': 849,
 'picture': 850,
 'getting': 851,
 'square': 852,
 'tone': 853,
 'hopes': 854,
 'shop': 855,
 'class': 856,
 'cloak': 857,
 'begin': 858,
 'hill': 859,
 'twice': 860,
 'passing': 861,
 'written': 862,
 'wrote': 863,
 'months': 864,
 'supposed': 865,
 'further': 866,
 'company': 867,
 'officers': 868,
 'disposition': 869,
 'receive': 870,
 'sainte': 871,
 'opening': 872,
 'agathe': 873,
 'proud': 874,
 'removed': 875,
 'miles': 876,
 'narrow': 877,
 'fetch': 878,
 'become': 879,
 'sleep': 880,
 'meeting': 881,
 'spoken': 882,
 'match': 883,
 'shook': 884,
 'prevented': 885,
 'thursday': 886,
 'library': 887,
 'greater': 888,
 'credit': 889,
 'highly': 890,
 'pounds': 891,
 'importance': 892,
 'attachment': 893,
 'pray': 894,
 'relations': 895,
 'especially': 896,
 'frequently': 897,
 'tea': 898,
 'burns': 899,
 'millie': 900,
 'youth': 901,
 'until': 902,
 'mistaken': 903,
 'please': 904,
 'wild': 905,
 'darkness': 906,
 'showed': 907,
 'wretched': 908,
 'marked': 909,
 'calling': 910,
 'voices': 911,
 'event': 912,
 'need': 913,
 'wide': 914,
 'understood': 915,
 'related': 916,
 'taste': 917,
 'estate': 918,
 'covered': 919,
 'listen': 920,
 'six': 921,
 'asking': 922,
 'sad': 923,
 'concern': 924,
 'intended': 925,
 'valentine': 926,
 'pleasing': 927,
 'promised': 928,
 'express': 929,
 'dislike': 930,
 'anybody': 931,
 'conduct': 932,
 'georgiana': 933,
 'john': 934,
 'eyre': 935,
 'gateshead': 936,
 'middle': 937,
 'walls': 938,
 'leading': 939,
 'station': 940,
 'hat': 941,
 'quickly': 942,
 'praise': 943,
 'attempt': 944,
 'raised': 945,
 'offered': 946,
 'distress': 947,
 'fortnight': 948,
 'latter': 949,
 'formed': 950,
 'empty': 951,
 'quietly': 952,
 'bohemian': 953,
 'acquainted': 954,
 'park': 955,
 'addressed': 956,
 "bennet's": 957,
 "jane's": 958,
 'compliment': 959,
 'exceedingly': 960,
 'building': 961,
 'gently': 962,
 'listening': 963,
 'smiling': 964,
 'bread': 965,
 'writing': 966,
 'pupil': 967,
 'teachers': 968,
 'avoid': 969,
 'joy': 970,
 'delighted': 971,
 'forgotten': 972,
 'stranger': 973,
 "'and": 974,
 'inquiries': 975,
 'persuaded': 976,
 'inclination': 977,
 'forget': 978,
 'gratitude': 979,
 'sake': 980,
 'humour': 981,
 'excellent': 982,
 'circumstance': 983,
 'favour': 984,
 'attentions': 985,
 'attended': 986,
 'phillips': 987,
 'wholly': 988,
 'hunsford': 989,
 'try': 990,
 'shoulders': 991,
 'putting': 992,
 "meaulnes'": 993,
 'stop': 994,
 'madame': 995,
 'wrong': 996,
 'ended': 997,
 'direction': 998,
 "it's": 999,
 "i've": 1000,
 ...}

In [ ]:
len(en_tokenizer.word_index)

12241

In [ ]:

# Step 6: Translation function
def translate(sentence):
    seq = en_tokenizer.texts_to_sequences([sentence])
    padded = pad_sequences(seq, maxlen=en_tensor.shape[1], padding='post')
    decoder_input = np.zeros((1, fr_tensor.shape[1]), dtype=np.int32)
    decoder_input[0][0] = fr_tokenizer.word_index.get('<sos>', 1)

    for i in range(1, fr_tensor.shape[1]):
        output = model([padded, decoder_input[:, :-1]], training=False)
        pred_id = tf.argmax(output[0, i-1]).numpy()
        decoder_input[0][i] = pred_id
        if pred_id == fr_tokenizer.word_index.get('<eos>'):
            break

    return ' '.join([fr_tokenizer.index_word.get(idx, '') for idx in decoder_input[0] if idx != 0])

# Step 7: Evaluation
results = []
for i in range(10):
    ref = [nltk.word_tokenize(french_sentences[i].replace('<sos>', '').replace('<eos>', '').strip())]
    pred = nltk.word_tokenize(translate(english_sentences[i]))
    bleu = sentence_bleu(ref, pred)
    rouge = rouge_scorer.RougeScorer(['rouge1', 'rouge2'], use_stemmer=True).score(' '.join(ref[0]), ' '.join(pred))
    results.append((english_sentences[i], french_sentences[i].replace('<sos>', '').replace('<eos>', '').strip(), ' '.join(pred), bleu, rouge['rouge1'].fmeasure, rouge['rouge2'].fmeasure))

import pandas as pd
pd.DataFrame(results, columns=["English", "French (Reference)", "Predicted French", "BLEU", "ROUGE-1", "ROUGE-2"])

/usr/local/lib/python3.11/dist-packages/nltk/translate/bleu_score.py:577: UserWarning:
The hypothesis contains 0 counts of 2-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
/usr/local/lib/python3.11/dist-packages/nltk/translate/bleu_score.py:577: UserWarning:
The hypothesis contains 0 counts of 3-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)
/usr/local/lib/python3.11/dist-packages/nltk/translate/bleu_score.py:577: UserWarning:
The hypothesis contains 0 counts of 4-gram overlaps.
Therefore the BLEU score evaluates to 0, independently of
how many N-gram overlaps of lower order it contains.
Consider using lower n-gram order or use SmoothingFunction()
  warnings.warn(_msg)

,English,French (Reference),Predicted French,BLEU,ROUGE-1,ROUGE-2
0,The Wanderer,Le grand Meaulnes,< OOV > eos,0.000000e+00,0.000000,0.000000
1,Alain-Fournier,Alain-Fournier,< OOV > eos,0.000000e+00,0.000000,0.000000
2,First Part,PREMIÈRE PARTIE,< OOV > eos,0.000000e+00,0.000000,0.000000
3,I,CHAPITRE PREMIER,< OOV > eos,0.000000e+00,0.000000,0.000000
4,THE BOARDER,LE PENSIONNAIRE,< OOV > eos,0.000000e+00,0.000000,0.000000
5,He arrived at our home on a Sunday of November...,Il arriva chez nous un dimanche de novembre 189-…,< OOV > à la route de la route de la route eos,9.594503e-232,0.105263,0.000000
6,"I still say 'our home,' although the house no ...","Je continue à dire « chez nous », bien que la ...",< OOV > que nous < OOV > que je < OOV > de < O...,1.051835e-231,0.260870,0.000000
7,We left that part of the country nearly fiftee...,Nous avons quitté le pays depuis bientôt quinz...,< OOV > que nous avons été bien de la < OOV > ...,1.037713e-231,0.200000,0.071429
8,We were living in the building of the Higher E...,Nous habitions les bâtiments du Cours Supérieu...,< OOV > dans la route de la route de galais eos,9.788429e-232,0.090909,0.000000
9,"My father, whom I used to call M. Seurel as di...","Mon père, que j’appelais M. Seurel, comme les ...",< OOV > de galais me dit la route et je me dit...,1.000369e-231,0.138889,0.000000

In [ ]:
import os
from google.colab import userdata



# Set environment variables for Kaggle API
os.environ['KAGGLE_USERNAME'] ="mohanrajmit"
os.environ['KAGGLE_KEY'] = "3bbbe7ee9dbe85615bfec6346e22510a"

print("Kaggle credentials set as environment variables.")

Kaggle credentials set as environment variables.

In [ ]:
#!/bin/bash
!kaggle datasets download bagavathypriya/english-to-tamil-data

Dataset URL: https://www.kaggle.com/datasets/bagavathypriya/english-to-tamil-data
License(s): unknown
Downloading english-to-tamil-data.zip to /content
  0% 0.00/9.29k [00:00<?, ?B/s]
100% 9.29k/9.29k [00:00<00:00, 11.6MB/s]

In [ ]:
!unzip /content/english-to-tamil-data.zip

Archive:  /content/english-to-tamil-data.zip
  inflating: tam.txt

In [ ]:
english_sentences = []
tamil_sentences = []

with open('/content/tam.txt', 'r', encoding='utf-8') as f:
    for line in f:
        parts = line.strip().split('\t')
        if len(parts) >= 2:
            english_sentences.append(parts[0])
            tamil_sentences.append(parts[1])

print(f"Number of English sentences: {len(english_sentences)}")
print(f"Number of Tamil sentences: {len(tamil_sentences)}")

Number of English sentences: 201
Number of Tamil sentences: 201

In [ ]:
english_sentences[0]

'I slept.'

In [ ]:
tamil_sentences[0]

'நான் தூங்கினேன்.'

In [ ]:
en_tokenizer, en_tensor = tokenize(english_sentences)
tamil_tokenizer, tamil_tensor = tokenize(tamil_sentences)
input_vocab_size = len(en_tokenizer.word_index) + 1
target_vocab_size = len(tamil_tokenizer.word_index) + 1

In [ ]:
tamil_tokenizer.word_index

{'<OOV>': 1,
 'நான்': 2,
 'அவள்': 3,
 'அவன்': 4,
 'டாம்': 5,
 'ஒரு': 6,
 'என்று': 7,
 'அவனுக்கு': 8,
 'தெரியும்': 9,
 'என்னிடம்': 10,
 'நீ': 11,
 'வேண்டும்': 12,
 'எனக்கு': 13,
 'நிறைய': 14,
 'என்ன': 15,
 'இது': 16,
 'இந்த': 17,
 'யார்': 18,
 'போய்': 19,
 'இருக்கிறது': 20,
 'அந்த': 21,
 'விரும்புகிறேன்': 22,
 'எப்பொழுது': 23,
 'நாங்கள்': 24,
 'உன்னிடம்': 25,
 'என்': 26,
 'பயம்': 27,
 'அவர்கள்': 28,
 'அவனைக்': 29,
 'அவளிடம்': 30,
 'அதை': 31,
 'ஓட': 32,
 'வந்தான்': 33,
 'எப்படி': 34,
 'சொன்னான்': 35,
 'எனக்குத்': 36,
 'பணம்': 37,
 'செல்ல': 38,
 'செய்து': 39,
 'வெளியே': 40,
 'மேரியுடன்': 41,
 'அமைதியாக': 42,
 'சிரித்தாள்': 43,
 'எங்கே': 44,
 'இரு': 45,
 'பார்க்கிறேன்': 46,
 'உன்': 47,
 'வந்து': 48,
 'பார்': 49,
 'ஆரம்பித்தான்': 50,
 'இருக்கிறார்கள்': 51,
 'என்னால்': 52,
 'சாப்பிட': 53,
 'முடியும்': 54,
 'வா': 55,
 'எங்களுக்கு': 56,
 'உதவி': 57,
 'இன்னும்': 58,
 'இப்பொழுது': 59,
 'போக': 60,
 'எங்களுடைய': 61,
 'என்னுடைய': 62,
 'முன்னால்': 63,
 'மூன்று': 64,
 'என்பது': 65,
 'போகத்': 66,
 'நடக்க': 67,
 'ஆடை': 68,
 'இதை': 69,
 'அவனுக்குக்': 70,
 'கொடுத்தாள்': 71,
 'அவனிடம்': 72,
 'அன்பாக': 73,
 'செய்ய': 74,
 'ரொம்ப': 75,
 'வேகமாக': 76,
 'நீங்கள்': 77,
 'ஏதாவது': 78,
 'மேரியை': 79,
 'கிளம்ப': 80,
 'பற்றி': 81,
 'உன்னை': 82,
 'உள்ளன': 83,
 'வருவான்': 84,
 'என': 85,
 'எதிர்': 86,
 'துண்டு': 87,
 'உங்களுக்கு': 88,
 'எல்லோரும்': 89,
 'தெரியுமா': 90,
 'என்றால்': 91,
 'விட்டு': 92,
 'பட்டாள்': 93,
 'வர': 94,
 'உங்களுடைய': 95,
 'முழுவதும்': 96,
 'மக்கள்': 97,
 'ஒவ்வொரு': 98,
 'விலை': 99,
 'வில்லை': 100,
 'கல்யாணம்': 101,
 'பொழுது': 102,
 'வார்த்தையைப்': 103,
 'பயன்': 104,
 'தூங்கினேன்': 105,
 'இருங்கள்': 106,
 'நடப்பேன்': 107,
 'யாருக்குத்': 108,
 'பேசு': 109,
 'தூங்கு': 110,
 'மழை': 111,
 'பெய்யலாம்': 112,
 'கடித்தாள்': 113,
 'அடித்தாள்': 114,
 'அன்பானவள்': 115,
 'அவளுக்கு': 116,
 'எட்டு': 117,
 'வயது': 118,
 'நாம்': 119,
 'இருக்கிறோம்': 120,
 'தொடர்பில்': 121,
 'மறுபடியும்': 122,
 'சந்திப்போம்': 123,
 'கொடு': 124,
 'சாப்பிட்டேன்': 125,
 'கையில்தான்': 126,
 'விட்டுவிடு': 127,
 'இதைக்': 128,
 'கேள்': 129,
 'பக்கம்தான்': 130,
 'வழி': 131,
 'என்னை': 132,
 'பொய்': 133,
 'சொல்லாதே': 134,
 'இப்பொழுதுதான்': 135,
 'விருப்பப்': 136,
 'படுகிறான்': 137,
 'தங்களுடைய': 138,
 'தந்தையார்': 139,
 'தூங்க': 140,
 'முடிகிறது': 141,
 'கையைத்': 142,
 'தூக்கு': 143,
 'நம்மால்': 144,
 'செய்': 145,
 'இருக்கிறான்': 146,
 'அவ்வளவு': 147,
 'தவறு': 148,
 'செய்தேன்': 149,
 'பள்ளிக்கு': 150,
 'நடந்து': 151,
 'செல்கிறேன்': 152,
 'அது': 153,
 'வீடு': 154,
 'அவைகள்': 155,
 'cd': 156,
 'கள்': 157,
 'நட': 158,
 'உன்னைத்': 159,
 'பின்பற்றுவோம்': 160,
 'அ': 161,
 'தொடர்வோம்': 162,
 'நாய்': 163,
 'ஜாக்கிரதை': 164,
 'சீக்கிரம்': 165,
 'திரும்பி': 166,
 'அவருக்கு': 167,
 'மகன்கள்': 168,
 'பனியில்': 169,
 'சறுக்கி': 170,
 'விளையாடுவது': 171,
 'செய்வது': 172,
 'விதமான': 173,
 'மகிழ்ச்சியிலிருக்கிறேன்': 174,
 'வலது': 175,
 'பக்கத்தை': 176,
 'கடைப்': 177,
 'பிடி': 178,
 'பாட': 179,
 'ஆரம்பித்தாள்': 180,
 'தீர்மானித்தாள்': 181,
 'படிக்க': 182,
 'வேண்டுமா': 183,
 'வருவது': 184,
 'நிச்சயம்': 185,
 'வீட்டிற்கு': 186,
 'வேண்டியிருந்தது': 187,
 'அணிய': 188,
 'அவனை': 189,
 'வரச்': 190,
 'சொன்னேன்': 191,
 'குறைவாக': 192,
 'பேசலாமா': 193,
 'இருக்கிறாள்': 194,
 'அருகில்': 195,
 'அமர்ந்தாள்': 196,
 'வாயை': 197,
 'மூடி': 198,
 'கவனி': 199,
 'சொல்': 200,
 'ஓடுகிறான்': 201,
 'உணவு': 202,
 'தட்டுப்பாடு': 203,
 'ஏற்பட்டது': 204,
 'ஆரம்பித்தோம்': 205,
 'ஆரம்பிக்கிறது': 206,
 'தயாராக': 207,
 'இருக்கிறீர்களா': 208,
 'பசை': 209,
 'இருக்கிறதா': 210,
 'பியானோ': 211,
 'வாசிக்கிறாளோ': 212,
 'சொல்வதைக்': 213,
 'கேட்காதீர்': 214,
 'எழுப்பு': 215,
 'நம்மைப்': 216,
 'தோன்றுகிறது': 217,
 'அவளோடு': 218,
 'நிச்சயமாகியிருக்கு': 219,
 'வெளி': 220,
 'நாட்டிற்குச்': 221,
 'உன்னைப்': 222,
 'பார்ப்பதில்': 223,
 'மகிழ்ச்சி': 224,
 'அடைகிறேன்': 225,
 'மகனைப்': 226,
 'பெருமைப்': 227,
 'படுகிறேன்': 228,
 'விட': 229,
 'உயரமாக': 230,
 'இருக்கிறேன்': 231,
 'தூங்குவதற்கு': 232,
 'முயற்சி': 233,
 'கொண்டிருக்கிறேன்': 234,
 'இதற்கு': 235,
 'கட்டணமில்லை': 236,
 'தூக்கத்திலிருந்து': 237,
 'எழுவதற்கான': 238,
 'நேரம்': 239,
 'கூட': 240,
 'யாரும்': 241,
 'பேசுவதில்லை': 242,
 'பந்தை': 243,
 'உருட்டி': 244,
 'விடு': 245,
 'முட்டைகளை': 246,
 'வேக': 247,
 'வைத்தாள்': 248,
 'அவனோடு': 249,
 'நடனம்': 250,
 'ஆடினாள்': 251,
 'புத்தகத்தைக்': 252,
 '2000': 253,
 'புத்தகங்கள்': 254,
 'ஆப்பிள்': 255,
 'இனிப்பாக': 256,
 'ஏரியில்': 257,
 'நீச்சலடித்தான்': 258,
 'ஆறு': 259,
 'மணிக்கு': 260,
 'முன்பு': 261,
 'வீட்': 262,
 'டிற்கு': 263,
 'எனக்குக்': 264,
 'கரடிகளைக': 265,
 'கண்டால்': 266,
 'கேக்கின்': 267,
 'பையன்': 268,
 'அழ': 269,
 'இதில்': 270,
 'தலையிடாதே': 271,
 'அனைவரும்': 272,
 'இருந்தோம்': 273,
 'வயோதிகர்களிடம்': 274,
 'ஜேப்படிகாரர்களிடம்': 275,
 'ஜாக்கிரதையாக': 276,
 'இருக்கவும்': 277,
 'குடித்துவிட்டு': 278,
 'வண்டி': 279,
 'ஓட்டாதே': 280,
 'எழுதப்': 281,
 'படிக்கத்': 282,
 'கிடைத்தது': 283,
 'பணமிருக்கிறது': 284,
 'இறந்து': 285,
 'போவதென்றால்': 286,
 'கயிற்றை': 287,
 'விட்டான்': 288,
 'வேலை': 289,
 'பளுவினால்': 290,
 'சோர்வாகயிருக்கிறேன்': 291,
 'டாக்ஸியிலிருந்து': 292,
 'இறங்கினேன்': 293,
 'சம்பந்தமில்லாத': 294,
 'விஷயம்': 295,
 'கிண்டலடித்தார்கள்': 296,
 'டாமும்': 297,
 'நானும்': 298,
 'நண்பர்கள்': 299,
 'உங்கள்': 300,
 'பிறந்த': 301,
 'நாள்': 302,
 'எப்போது': 303,
 'அங்கே': 304,
 'சென்றார்கள்': 305,
 'சைக்கிள்': 306,
 'ஓட்டத்': 307,
 'பணக்காரராக': 308,
 'விருப்பமா': 309,
 'அவர்களுக்கு': 310,
 'பாம்புகள்': 311,
 'நீச்சல்': 312,
 'மீது': 313,
 'பற்று': 314,
 'உண்டு': 315,
 'எனக்குப்': 316,
 'பதிலாக': 317,
 'சேன்றான்': 318,
 'கடல்': 319,
 'விடுகிறேன்': 320,
 'வெறுக்கிற': 321,
 'மாதிரி': 322,
 'தெரிகிறது': 323,
 'நிச்சயிக்கப்': 324,
 'திருமணம்': 325,
 'வைக்கப்': 326,
 'நெருக்கமாக': 327,
 'நின்றாள்': 328,
 'சீடி': 329,
 'அவளுக்குச்': 330,
 'சொந்தமானது': 331,
 'திருடனுக்குப்': 332,
 'பின்னால்': 333,
 'ஓடினோம்': 334,
 'செய்யத்': 335,
 'திட்டமிட்டிருக்கிறாய்': 336,
 'சதுரத்திற்கு': 337,
 'நான்கு': 338,
 'பக்கங்கள்': 339,
 'கணக்கிற்கு': 340,
 'மாற்று': 341,
 'கடிதம்': 342,
 'எழுதினார்களா': 343,
 'எங்களை': 344,
 'செய்யும்படி': 345,
 'கேட்டான்': 346,
 'ஒவ்வொருவருக்கும்': 347,
 'அறிமுகமானவன்': 348,
 'திட்டத்திற்கு': 349,
 'எதிர்ப்புத்': 350,
 'தெரிவித்தான்': 351,
 'வேண்டுமென': 352,
 'அவர்': 353,
 'நண்பரா': 354,
 'செய்தி': 355,
 'பரவியது': 356,
 'இருக்கு': 357,
 'கண்டுபிடிக்க': 358,
 'முடியவில்லை': 359,
 'கோபமாக': 360,
 'இருப்பாய்': 361,
 'எண்ணினேன்': 362,
 'இங்கே': 363,
 'அமருங்கள்': 364,
 'தயவு': 365,
 'செயது': 366,
 'காத்திருங்கள்': 367,
 'அறையை': 368,
 'சென்றாள்': 369,
 'மெதுவாகவும்': 370,
 'தெளிவாகவும்': 371,
 'பேசுங்கள்': 372,
 'வானம்': 373,
 'நட்சத்திரங்கள்': 374,
 'இருக்கின்றன': 375,
 'உடனே': 376,
 'என்னைப்': 377,
 'பார்க்கவும்': 378,
 'பேனாக்கள்': 379,
 'இருக்கின்றனவா': 380,
 'தந்தையருகில்': 381,
 'அமரவும்': 382,
 'ஜோடி': 383,
 'காலணிகளை': 384,
 'வாங்கினேன்': 385,
 'கீழ்': 386,
 'தளத்தில்': 387,
 'வசிக்கிறேன்': 388,
 'டாமுக்கும்': 389,
 'ஜானுக்கும்': 390,
 'இடையில்': 391,
 'அமர்ந்தேன்': 392,
 'அழகான': 393,
 'அணிந்திருந்தாள்': 394,
 'ஜப்பான்': 395,
 'வந்தாய்': 396,
 'பைத்தியம்': 397,
 'எண்ணுகிறார்கள்': 398,
 'உயிருடனிருக்கிறான்': 399,
 'எண்ணுகிறேன்': 400,
 'கொஞ்சம்': 401,
 'கேட்டாள்': 402,
 'அதைப்': 403,
 'அவனே': 404,
 'எப்ப': 405,
 'உனக்குத்': 406,
 'நாயின்': 407,
 'படத்தை': 408,
 'வரைந்தான்': 409,
 'மற்றவர்களுக்கு': 410,
 'முன்னே': 411,
 'வந்தேன்': 412,
 'ஊரின்': 413,
 'அங்குலமும்': 414,
 'டாமிடம்': 415,
 'பகிர்ந்துகொண்டு': 416,
 'இருக்கவில்லை': 417,
 'எதற்கும்': 418,
 'பயப்படுவதில்லை': 419,
 'முட்டைகளின்': 420,
 'அதிகரித்துக்': 421,
 'கொண்டிருக்கிறது': 422,
 'தொப்பியின்': 423,
 'இவர்களில்': 424,
 'உன்னுடைய': 425,
 'சகோதரர்': 426,
 'மணி': 427,
 'ஒலித்தப்': 428,
 'பிறகு': 429,
 'அபாயத்தை': 430,
 'அறிந்திருக்க': 431,
 'சின்ன': 432,
 'கேக்குத்': 433,
 'தொண்டையில்': 434,
 'சிக்கிக்': 435,
 'கொண்டது': 436,
 'பள்ளி': 437,
 'கூடம்': 438,
 'சிறைச்சாலையைப்': 439,
 'போல': 440,
 'பதில்': 441,
 'சொல்வது': 442,
 'என்பதில்': 443,
 'உறுதியாக': 444,
 'இல்லை': 445,
 'இங்கிருந்து': 446,
 'சுலபமான': 447,
 'வழியில்லை': 448,
 'மோசமான': 449,
 'நாய்கள்': 450,
 'டாமை': 451,
 'தாக்கின': 452,
 'வருடத்திற்கு': 453,
 'ஆஸ்திரேலியாவில்': 454,
 'இருந்தார்': 455,
 'நடைப்': 456,
 'பெற்றது': 457,
 'பாஸ்போர்ட்டைஎங்கே': 458,
 'வைத்திருக்கிறாய்': 459,
 'உடல்': 460,
 'நிலை': 461,
 'சரியில்லாததனால்': 462,
 'அவனால்': 463,
 'இயலாது': 464,
 'நட்புக்குத்': 465,
 'தேவை': 466,
 'பரஸ்பர': 467,
 'நம்பிக்கை': 468,
 'மேரியின்': 469,
 'விரலில்': 470,
 'மோதிரத்தை': 471,
 'அணிவித்தான்': 472,
 'பத்திரிக்கையை': 473,
 'மேலோட்டமாகப்': 474,
 'பார்த்தாள்': 475,
 'மதியம்': 476,
 'அழுதுகொண்டேயிருக்கிறான்': 477,
 'தொடர்பிலிருந்துருக்கிறான்': 478,
 'அல்லது': 479,
 'தொடர்பிலிருக்கிறான்': 480,
 'காலத்தில்': 481,
 'விமானியாக': 482,
 'ஓடிவிட்டால்': 483,
 'அவரால்': 484,
 'எங்கு': 485,
 'இரயிலில்': 486,
 'ஜேப்படி': 487,
 'அடிக்கப்': 488,
 'பட்டிருந்தது': 489,
 'ஏதோ': 490,
 'மற்றும்': 491,
 'இருட்டாக': 492,
 'இருக்கும்': 493,
 'விரும்புவதில்லை': 494,
 'பேசியப்': 495,
 'அமைதி': 496,
 'காத்தார்கள்': 497,
 'நள்ளிரவு': 498,
 'வரை': 499,
 'எங்களுடன்': 500,
 'குடித்தார்': 501,
 'ஒட்டினக்': 502,
 'காரில்': 503,
 'எப்பொழுதும்': 504,
 'இருந்ததில்லை': 505,
 'ஞாயிற்றுக்': 506,
 'கிழமையும்': 507,
 'தேவாலயத்துக்குச்': 508,
 'செல்கிறான்': 509,
 'படுத்துவதாக': 510,
 'தெரியவில்லை': 511,
 'தங்கை': 512,
 'இள': 513,
 'வயதிலேய': 514,
 'கொண்டாள்': 515,
 'ஏன்': 516,
 'நாமிருவரும்': 517,
 'சேர்ந்து': 518,
 'செய்வோமென்று': 519,
 'பரிந்துரைத்தான்': 520,
 'ஆச்சரியமடைகிறேன்': 521,
 'ஒருவனால்': 522,
 'மட்டுமே': 523,
 'முடியாது': 524,
 'நினைக்கிறேன்': 525,
 'கூறினார்': 526,
 'கண்ணாடி': 527,
 'வீட்டில்': 528,
 'வசிப்பவகள்': 529,
 'கல்லை': 530,
 'எறியக்': 531,
 'கூடாது': 532,
 'ஒருவர்': 533,
 'படுத்துவதைக்': 534,
 'கேட்டு': 535,
 'நாளாகிறது': 536,
 'வேலையாட்கள்': 537,
 'மகிழ்ச்சியாக': 538,
 'இருக்க': 539,
 'வேண்டுமென்றால்': 540,
 'கணிசமான': 541,
 'சம்பளம்': 542,
 'தர': 543,
 'என்னுடையத்': 544,
 'தவறினால்': 545,
 'கேக்கானதுக்': 546,
 'கருகிப்': 547,
 'போனது': 548,
 'தோலைப்': 549,
 'பேசியில்': 550,
 'பேசிக்': 551,
 'கொண்டிருந்ததால்': 552,
 'நேரத்தைக்': 553,
 'கவனிக்க': 554}

In [ ]:
en_tensor.shape

(201, 40)

In [ ]:
tamil_tensor.shape

(201, 40)

In [ ]:

# Step 5: Compile and train
model = Transformer(input_vocab=input_vocab_size, target_vocab=target_vocab_size,
                    d_model=64, num_heads=4, dff=128, pe_input=en_tensor.shape[1], pe_target=tamil_tensor.shape[1])
model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])
model.fit([en_tensor, tamil_tensor[:, :-1]],tamil_tensor[:, 1:], epochs=1000, batch_size=32)

Epoch 1/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 9s 397ms/step - accuracy: 0.5986 - loss: 6.0666
Epoch 2/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9203 - loss: 1.8679
Epoch 3/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9175 - loss: 1.7860
Epoch 4/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9178 - loss: 1.0007
Epoch 5/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9196 - loss: 0.9098
Epoch 6/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9183 - loss: 0.8219
Epoch 7/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9179 - loss: 0.8009
Epoch 8/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9197 - loss: 0.7812
Epoch 9/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9189 - loss: 0.7821
Epoch 10/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9210 - loss: 0.7615
Epoch 11/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9183 - loss: 0.7799
Epoch 12/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9191 - loss: 0.7733
Epoch 13/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9194 - loss: 0.7713
Epoch 14/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9184 - loss: 0.7793
Epoch 15/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9209 - loss: 0.7596
Epoch 16/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9226 - loss: 0.7429
Epoch 17/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9185 - loss: 0.7774
Epoch 18/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9212 - loss: 0.7517
Epoch 19/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9177 - loss: 0.7840
Epoch 20/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9183 - loss: 0.7786
Epoch 21/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9219 - loss: 0.7491
Epoch 22/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9212 - loss: 0.7566
Epoch 23/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9197 - loss: 0.7673
Epoch 24/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9204 - loss: 0.7581
Epoch 25/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9201 - loss: 0.7595
Epoch 26/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9213 - loss: 0.7492
Epoch 27/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9215 - loss: 0.7478
Epoch 28/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9172 - loss: 0.7811
Epoch 29/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9209 - loss: 0.7512
Epoch 30/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9175 - loss: 0.7560
Epoch 31/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9188 - loss: 0.5960
Epoch 32/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9183 - loss: 0.5638
Epoch 33/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9180 - loss: 0.5526
Epoch 34/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9202 - loss: 0.5391
Epoch 35/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9197 - loss: 0.5400
Epoch 36/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9209 - loss: 0.5277
Epoch 37/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9157 - loss: 0.5518
Epoch 38/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9162 - loss: 0.5409
Epoch 39/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9201 - loss: 0.5063
Epoch 40/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9204 - loss: 0.4981
Epoch 41/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9183 - loss: 0.5090
Epoch 42/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9211 - loss: 0.4871
Epoch 43/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9199 - loss: 0.4950
Epoch 44/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9197 - loss: 0.4963
Epoch 45/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9216 - loss: 0.4796
Epoch 46/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9220 - loss: 0.4781
Epoch 47/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9215 - loss: 0.4808
Epoch 48/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9194 - loss: 0.4938
Epoch 49/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9174 - loss: 0.5012
Epoch 50/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9210 - loss: 0.4779
Epoch 51/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9221 - loss: 0.4704
Epoch 52/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9172 - loss: 0.4933
Epoch 53/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9180 - loss: 0.4883
Epoch 54/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9215 - loss: 0.4631
Epoch 55/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9196 - loss: 0.4719
Epoch 56/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9201 - loss: 0.4578
Epoch 57/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9200 - loss: 0.4527
Epoch 58/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9165 - loss: 0.4708
Epoch 59/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9197 - loss: 0.4537
Epoch 60/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9212 - loss: 0.4445
Epoch 61/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9188 - loss: 0.4490
Epoch 62/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9188 - loss: 0.4487
Epoch 63/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9209 - loss: 0.4359
Epoch 64/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9224 - loss: 0.4227
Epoch 65/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9189 - loss: 0.4442
Epoch 66/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9223 - loss: 0.4199
Epoch 67/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9229 - loss: 0.4170
Epoch 68/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9214 - loss: 0.4191
Epoch 69/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9218 - loss: 0.4184
Epoch 70/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9199 - loss: 0.4264
Epoch 71/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9232 - loss: 0.4032
Epoch 72/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9216 - loss: 0.4077
Epoch 73/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9198 - loss: 0.4099
Epoch 74/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9229 - loss: 0.3940
Epoch 75/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9232 - loss: 0.3917
Epoch 76/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9210 - loss: 0.3901
Epoch 77/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9233 - loss: 0.3763
Epoch 78/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9213 - loss: 0.3790
Epoch 79/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9235 - loss: 0.3704
Epoch 80/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9237 - loss: 0.3528
Epoch 81/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9227 - loss: 0.3544
Epoch 82/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9197 - loss: 0.3614
Epoch 83/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9239 - loss: 0.3392
Epoch 84/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9235 - loss: 0.3356
Epoch 85/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9251 - loss: 0.3171
Epoch 86/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9260 - loss: 0.3102
Epoch 87/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9264 - loss: 0.3193
Epoch 88/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9268 - loss: 0.3027
Epoch 89/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9232 - loss: 0.3207
Epoch 90/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9269 - loss: 0.3015
Epoch 91/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9243 - loss: 0.3166
Epoch 92/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9265 - loss: 0.3105
Epoch 93/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9236 - loss: 0.3138
Epoch 94/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9280 - loss: 0.2941
Epoch 95/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9283 - loss: 0.2949
Epoch 96/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9259 - loss: 0.2964
Epoch 97/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9272 - loss: 0.2843
Epoch 98/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9255 - loss: 0.2940
Epoch 99/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9250 - loss: 0.2851
Epoch 100/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9296 - loss: 0.2726
Epoch 101/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9282 - loss: 0.2732
Epoch 102/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9261 - loss: 0.2782
Epoch 103/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9281 - loss: 0.2730
Epoch 104/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9275 - loss: 0.2744
Epoch 105/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9243 - loss: 0.2837
Epoch 106/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9299 - loss: 0.2685
Epoch 107/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9273 - loss: 0.2723
Epoch 108/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9261 - loss: 0.2775
Epoch 109/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9310 - loss: 0.2585
Epoch 110/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9299 - loss: 0.2567
Epoch 111/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9266 - loss: 0.2672
Epoch 112/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9283 - loss: 0.2651
Epoch 113/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9289 - loss: 0.2508
Epoch 114/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9266 - loss: 0.2581
Epoch 115/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9289 - loss: 0.2517
Epoch 116/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9306 - loss: 0.2470
Epoch 117/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9308 - loss: 0.2444
Epoch 118/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9303 - loss: 0.2486
Epoch 119/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9293 - loss: 0.2516
Epoch 120/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9349 - loss: 0.2396
Epoch 121/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9325 - loss: 0.2372
Epoch 122/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9311 - loss: 0.2424
Epoch 123/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9307 - loss: 0.2424
Epoch 124/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9296 - loss: 0.2451
Epoch 125/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9318 - loss: 0.2417
Epoch 126/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9325 - loss: 0.2382
Epoch 127/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9256 - loss: 0.2470
Epoch 128/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9320 - loss: 0.2381
Epoch 129/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9315 - loss: 0.2352
Epoch 130/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9341 - loss: 0.2215
Epoch 131/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9323 - loss: 0.2292
Epoch 132/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9317 - loss: 0.2291
Epoch 133/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9301 - loss: 0.2282
Epoch 134/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9349 - loss: 0.2211
Epoch 135/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9327 - loss: 0.2282
Epoch 136/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9298 - loss: 0.2454
Epoch 137/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9313 - loss: 0.2325
Epoch 138/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9323 - loss: 0.2269
Epoch 139/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9334 - loss: 0.2213
Epoch 140/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9302 - loss: 0.2351
Epoch 141/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9319 - loss: 0.2296
Epoch 142/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9301 - loss: 0.2278
Epoch 143/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9311 - loss: 0.2309
Epoch 144/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9331 - loss: 0.2167
Epoch 145/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9348 - loss: 0.2147
Epoch 146/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9422 - loss: 0.1971
Epoch 147/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9338 - loss: 0.2100
Epoch 148/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9364 - loss: 0.2011
Epoch 149/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9381 - loss: 0.1973
Epoch 150/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9389 - loss: 0.1933
Epoch 151/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9362 - loss: 0.2045
Epoch 152/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9351 - loss: 0.2053
Epoch 153/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9383 - loss: 0.2026
Epoch 154/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9350 - loss: 0.2117
Epoch 155/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9370 - loss: 0.2153
Epoch 156/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9362 - loss: 0.2061
Epoch 157/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9356 - loss: 0.2092
Epoch 158/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9373 - loss: 0.1981
Epoch 159/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9342 - loss: 0.2151
Epoch 160/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9319 - loss: 0.2521
Epoch 161/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9351 - loss: 0.2277
Epoch 162/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9332 - loss: 0.2341
Epoch 163/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9356 - loss: 0.2116
Epoch 164/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9342 - loss: 0.2120
Epoch 165/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9424 - loss: 0.1939
Epoch 166/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9412 - loss: 0.1920
Epoch 167/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9380 - loss: 0.1929
Epoch 168/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9423 - loss: 0.1881
Epoch 169/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9382 - loss: 0.1925
Epoch 170/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9370 - loss: 0.1967
Epoch 171/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9369 - loss: 0.2031
Epoch 172/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9398 - loss: 0.1891
Epoch 173/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9412 - loss: 0.1833
Epoch 174/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9411 - loss: 0.1885
Epoch 175/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9392 - loss: 0.1960
Epoch 176/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9377 - loss: 0.2060
Epoch 177/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9414 - loss: 0.1901
Epoch 178/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9410 - loss: 0.1871
Epoch 179/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9429 - loss: 0.1802
Epoch 180/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9422 - loss: 0.1788
Epoch 181/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9427 - loss: 0.1792
Epoch 182/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9385 - loss: 0.1928
Epoch 183/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9384 - loss: 0.1859
Epoch 184/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9403 - loss: 0.1874
Epoch 185/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9435 - loss: 0.1795
Epoch 186/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9440 - loss: 0.1787
Epoch 187/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9433 - loss: 0.1774
Epoch 188/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9430 - loss: 0.1787
Epoch 189/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9394 - loss: 0.1885
Epoch 190/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9400 - loss: 0.1924
Epoch 191/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9379 - loss: 0.1923
Epoch 192/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9391 - loss: 0.1923
Epoch 193/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9373 - loss: 0.1945
Epoch 194/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9407 - loss: 0.1866
Epoch 195/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9418 - loss: 0.1832
Epoch 196/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9441 - loss: 0.1777
Epoch 197/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9450 - loss: 0.1742
Epoch 198/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9464 - loss: 0.1667
Epoch 199/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9434 - loss: 0.1696
Epoch 200/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9512 - loss: 0.1570
Epoch 201/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9442 - loss: 0.1651
Epoch 202/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9447 - loss: 0.1642
Epoch 203/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9469 - loss: 0.1645
Epoch 204/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9480 - loss: 0.1687
Epoch 205/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9402 - loss: 0.1950
Epoch 206/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9420 - loss: 0.1867
Epoch 207/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9406 - loss: 0.1967
Epoch 208/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9428 - loss: 0.1850
Epoch 209/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9462 - loss: 0.1693
Epoch 210/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9471 - loss: 0.1614
Epoch 211/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9504 - loss: 0.1620
Epoch 212/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9458 - loss: 0.1643
Epoch 213/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9482 - loss: 0.1591
Epoch 214/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9469 - loss: 0.1651
Epoch 215/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9474 - loss: 0.1606
Epoch 216/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9445 - loss: 0.1714
Epoch 217/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9481 - loss: 0.1566
Epoch 218/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9422 - loss: 0.1783
Epoch 219/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9420 - loss: 0.1952
Epoch 220/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9408 - loss: 0.1953
Epoch 221/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9416 - loss: 0.1876
Epoch 222/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9389 - loss: 0.1951
Epoch 223/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9437 - loss: 0.1725
Epoch 224/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9421 - loss: 0.1774
Epoch 225/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9367 - loss: 0.1961
Epoch 226/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9422 - loss: 0.1840
Epoch 227/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9384 - loss: 0.2321
Epoch 228/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9388 - loss: 0.1978
Epoch 229/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9414 - loss: 0.1826
Epoch 230/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9469 - loss: 0.1665
Epoch 231/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9499 - loss: 0.1588
Epoch 232/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9537 - loss: 0.1483
Epoch 233/1000
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9552 - loss: 0.1414
Epoch 234/1000

In [ ]:
# Step 6: Translation function
def translate_tamil(sentence):
    seq = en_tokenizer.texts_to_sequences([sentence])
    padded = pad_sequences(seq, maxlen=en_tensor.shape[1], padding='post')
    decoder_input = np.zeros((1, tamil_tensor.shape[1]), dtype=np.int32)
    decoder_input[0][0] = tamil_tokenizer.word_index.get('<sos>', 1)

    for i in range(1, tamil_tensor.shape[1]):
        output = model([padded, decoder_input[:, :-1]], training=False)
        pred_id = tf.argmax(output[0, i-1]).numpy()
        decoder_input[0][i] = pred_id
        if pred_id == tamil_tokenizer.word_index.get('<eos>'):
            break

    return ' '.join([tamil_tokenizer.index_word.get(idx, '') for idx in decoder_input[0] if idx != 0])

# Example usage with an unknown English sentence
unknown_english_sentence = "how are you?"
translated_tamil_sentence = translate_tamil(unknown_english_sentence)
print(f"Original English: {unknown_english_sentence}")
print(f"Translated Tamil: {translated_tamil_sentence}")

Original English: how are you?
Translated Tamil: <OOV> விரும்புகிறேன்